multiversx/mx-sdk-rs

- elrond-wasm-debug/Cargo.toml
- elrond-wasm-debug/src/ext_mock.rs
- elrond-wasm-derive/Cargo.toml
- elrond-wasm-derive/src/contract_gen_event.rs
- elrond-wasm-node/Cargo.toml
- elrond-wasm/Cargo.toml
- elrond-wasm/src/io/finish.rs
- elrond-wasm/src/lib.rs
- elrond-wasm/src/types/h256.rs
minor refactoring, testing util
> Unit test capabilities

- modules/elrond-wasm-module-features/Cargo.toml
- modules/elrond-wasm-module-features/README.md
Missing elements from Cargo.toml
> feature module publish fix

- Cargo.toml
- README.md
- elrond-wasm-derive/src/arg_str_serialize.rs
- elrond-wasm/src/io/arg_serialize.rs
- elrond-wasm/src/lib.rs
- modules/elrond-wasm-module-features/src/lib.rs
- modules/elrond-wasm-module-pause/Cargo.toml
- modules/elrond-wasm-module-pause/README.md
- modules/elrond-wasm-module-pause/src/lib.rs
- test-contracts/use-module/Cargo.toml
- test-contracts/use-module/src/lib.rs
Also fixed a typo and some small tweaks that will not published yet.
> Pause standard module

- Cargo.toml
- build-wasm.sh
- elrond-wasm-debug/src/async_data.rs
- elrond-wasm-debug/src/blockchain_mock.rs
- elrond-wasm-debug/src/execute_mandos.rs
- elrond-wasm-debug/src/ext_mock.rs
- elrond-wasm-debug/src/lib.rs
- elrond-wasm-derive/src/function_selector.rs
- test-contracts/async/Cargo.toml
- test-contracts/async/async-alice/src/lib.rs
- test-contracts/async/src/lib.rs
- test-contracts/async/tests/async_mandos.rs
- tools/test-gen/src/main.rs
Async call support in elrond-wasm-debug + async call tests migrated
> Mandos - async calls

- examples/crowdfunding/snippets.sh
Add extra snippets in `examples/crowdfunding/snippets.sh`, for interacting with the Crowdfunding contract.
> Snippets in crowdfunding

- examples/crowdfunding/src/lib.rs
Add the `currentFunds` view and the empty file `testnet.toml`.
> Crowdfunding template adjustments

- elrond-wasm-debug/src/execute_mandos.rs
- examples/crowdfunding-erc20/tests/mandos_test.rs
- examples/lottery-erc20/tests/mandos_test.rs
- mandos/src/parse_util.rs
The crowdfunding-erc20 unveiled an issue in mandos.
Also some other test fixes.
> Mandos-rs test fixes

- mandos/README.md
mandos crate README.md was missing
> mandos readme

- contracts/benchmarks/str-repeat/src/lib.rs
- contracts/benchmarks/str-repeat/tests/mandos_test.rs
- contracts/feature-tests/basic-features/mandos/storage_clear.scen.json
- contracts/feature-tests/basic-features/src/lib.rs
- contracts/feature-tests/basic-features/tests/basic_features_mandos.rs
- elrond-wasm-derive/src/contract_gen.rs
- elrond-wasm-derive/src/contract_gen_method.rs
- elrond-wasm-derive/src/contract_gen_payable.rs
- elrond-wasm-derive/src/contract_gen_storage.rs
- elrond-wasm-derive/src/parse_attr.rs
- elrond-wasm/src/types/boxed_bytes.rs
- elrond-wasm/src/types/h256.rs
> Macro storage clear

- contracts/examples/multisig/src/lib.rs
- contracts/examples/multisig/src/user_role.rs
Multisig contract improvement.
See git issue for more info.
> Multisig - Rewrite the UserRole `can_*` methods to account for all possible scenarios

- contracts/examples/multisig/mandos/changeBoard.scen.json
- contracts/examples/multisig/mandos/steps/sign_unsign_bad_action.steps.json
- contracts/examples/multisig/src/lib.rs
Github issue: https://github.com/ElrondNetwork/elrond-wasm-rs/issues/64
> multisig - sign operation checks that action exists

- contracts/examples/multisig/mandos/steps/add_bm.steps.json
- contracts/examples/multisig/src/lib.rs
> Multisig - extracted getActionValidSignerCount view

- contracts/examples/multisig/mandos/deployAdder_then_call.scen.json
- contracts/examples/multisig/mandos/deployFactorial.scen.json
- contracts/examples/multisig/mandos/steps/deploy.steps.json
- contracts/examples/multisig/src/lib.rs
> Multisig - renamed board size to num board members 

- contracts/examples/multisig/mandos/deployAdder_then_call.scen.json
- contracts/examples/multisig/src/lib.rs
> Multisig - clean up storage before performing async_call

- contracts/examples/crowdfunding-egld/src/lib.rs
- contracts/examples/crypto-bubbles/src/lib.rs
- contracts/examples/lottery-egld/src/lib.rs
- contracts/examples/lottery-erc20/src/lib.rs
- contracts/examples/lottery-esdt/src/lib.rs
- contracts/examples/lottery-esdt/src/lottery_info.rs
- contracts/examples/multisig/src/action.rs
- contracts/examples/multisig/src/lib.rs
- contracts/examples/multisig/src/user_role.rs
- contracts/feature-tests/basic-features/mandos/send_tx.scen.json
- contracts/feature-tests/basic-features/src/lib.rs
- elrond-codec-derive/tests/enum_derive_test.rs
- elrond-wasm-debug/src/ext_mock.rs
- elrond-wasm-derive/src/snippets.rs
- elrond-wasm-node/src/ext.rs
- elrond-wasm/src/lib.rs
> Multisig - send tx with message

- contracts/feature-tests/abi-tester/abi_test_expected.abi.json
- contracts/feature-tests/abi-tester/src/lib.rs
- elrond-wasm-debug/src/abi_json/endpoint_abi_json.rs
- elrond-wasm-derive/src/abi_gen.rs
- elrond-wasm-derive/src/contract_gen_method.rs
- elrond-wasm-derive/src/parse_attr.rs
- elrond-wasm/src/abi/endpoint_abi.rs
- elrond-wasm/src/abi/type_abi.rs
- elrond-wasm/src/types/multi_result.rs
- elrond-wasm/src/types/sc_result.rs
ABI can generate output names via annotation.
> ABI generation - output names

- contracts/examples/ping-pong-egld/mandos/ping-pong-call-ping-before-beginning.scen.json
- contracts/examples/ping-pong-egld/mandos/ping-pong-call-ping-second-user.scen.json
- contracts/examples/ping-pong-egld/mandos/ping-pong-call-ping-twice.scen.json
- contracts/examples/ping-pong-egld/mandos/ping-pong-call-ping-wrong-ammount.scen.json
- contracts/examples/ping-pong-egld/mandos/ping-pong-call-ping.scen.json
- contracts/examples/ping-pong-egld/mandos/ping-pong-call-pong-all-after-pong.scen.json
- contracts/examples/ping-pong-egld/mandos/ping-pong-call-pong-all.scen.json
- contracts/examples/ping-pong-egld/mandos/ping-pong-call-pong-before-deadline.scen.json
- contracts/examples/ping-pong-egld/mandos/ping-pong-call-pong-twice.scen.json
- contracts/examples/ping-pong-egld/mandos/ping-pong-call-pong-without-ping.scen.json
- contracts/examples/ping-pong-egld/mandos/ping-pong-call-pong.scen.json
- contracts/examples/ping-pong-egld/mandos/ping-pong-init.scen.json
- contracts/examples/ping-pong-egld/tests/mandos_test.rs
- mandos/src/scenario_raw.rs
Also txId in mandos-rs was not optional, unlike mandos-go. Fixed.
> ping-pong-egld test fixes

- contracts/examples/multisig/mandos/changeQuorum.scen.json
- contracts/examples/multisig/src/action.rs
- contracts/examples/multisig/src/lib.rs
Endpoint that spews out **everything** about actions.
> multisig - getPendingActionFullInfo

- contracts/examples/multisig/mandos/deploy_duplicate_bm.scen.json
- contracts/examples/multisig/src/lib.rs
> multisig - prevent duplicate board members on init

- contracts/feature-tests/abi-tester/abi_test_expected.abi.json
- contracts/feature-tests/abi-tester/src/abi_enum.rs
- contracts/feature-tests/abi-tester/src/abi_test_type.rs
- contracts/feature-tests/abi-tester/src/lib.rs
- contracts/feature-tests/abi-tester/src/only_nested.rs
- elrond-wasm-debug/src/abi_json/type_abi_json.rs
- elrond-wasm-derive/src/abi_derive.rs
- elrond-wasm/src/abi/type_description.rs
Also generating enum variant discriinants in ABI.
> abi generation - enum discriminants

- tools/test-gen/src/main.rs
Modified test-gen-tool to accept input parameters 
Implement reading from directory instead of copy-paste
> modified test-gen-tool

- contracts/feature-tests/basic-features/mandos/storage_mapper_vec.scen.json
- contracts/feature-tests/basic-features/src/lib.rs
- elrond-wasm/src/storage/mappers/vec_mapper.rs
> VecMapper len() method

- contracts/examples/multisig/mandos/changeBoard.scen.json
- contracts/examples/multisig/src/lib.rs
> multisig - quorum check when converting board member to proposer

- Cargo.toml
- contracts/feature-tests/async/forwarder-same-shard-raw/Cargo.toml
- contracts/feature-tests/async/forwarder-same-shard-raw/elrond.json
- contracts/feature-tests/async/forwarder-same-shard-raw/src/lib.rs
- contracts/feature-tests/async/forwarder-same-shard-raw/wasm/Cargo.toml
- contracts/feature-tests/async/forwarder-same-shard-raw/wasm/src/lib.rs
- elrond-wasm-debug/src/api/send_api_mock.rs
- elrond-wasm-node/src/api/send_api_node.rs
- elrond-wasm/src/api/send_api.rs
- elrond-wasm/src/types/interaction/arg_buffer.rs
Low-level functionality to extract results after an executeOnDestContext call.
> executeOnDestContext - retrieve raw results

- contracts/feature-tests/abi-tester/abi_test_expected.abi.json
- contracts/feature-tests/abi-tester/src/lib.rs
- contracts/feature-tests/abi-tester/src/only_nested.rs
- elrond-wasm-debug/src/abi_json/contract_abi_json.rs
- elrond-wasm-debug/src/abi_json/endpoint_abi_json.rs
- elrond-wasm-derive/src/generate/abi_gen.rs
- elrond-wasm/src/abi/contract_abi.rs
Constructor inputs, outputs, docs & payable info in ABI.
> ABI - constructor representation

- contracts/examples/esdt-nft-marketplace/src/lib.rs
Original owner can withdraw if no bids were made.
> withdraw functionality

- contracts/examples/esdt-nft-marketplace/mandos/specific_token_auctioned.scen.json
- elrond-wasm-node/src/api/blockchain_api_node.rs
Hash is now ignored when calling get_esdt_token_data
> Nft marketplace debugging

- contracts/examples/ping-pong-egld/wasm/Cargo.toml
- contracts/feature-tests/abi-tester/abi_tester_expected.abi.json
- contracts/feature-tests/abi-tester/src/lib.rs
- elrond-wasm-debug/src/execute_mandos.rs
- elrond-wasm/src/lib.rs
- elrond-wasm/src/types/general/esdt_local_role.rs
- elrond-wasm/src/types/io/sc_result.rs
Also used the macro for its serializer, in this case it works.
Upgraded to the Try trait v2 for SCResult, since this seems to be required since `rustc 1.54.0-nightly (4e3e6db01 2021-05-18)`
> EsdtLocalRole full type ABI

- elrond-wasm/src/types/interaction/arg_buffer.rs
- elrond-wasm/src/types/io/sc_error.rs
- elrond-wasm/src/types/io/sc_result.rs
Clone implementation for ArgBuffer
Added From<Result> for SCResult, where the error is DecodeError.
> arg buffer Clone trait impl

- contracts/feature-tests/basic-features/mandos/storage_mapper_token_attributes.scen.json
- elrond-wasm/src/storage/mappers/token_attributes_mapper.rs
Added ".attr" suffix in token attributes mapper
> Added suffix to token attributes value in mapper

- contracts/feature-tests/basic-features/src/echo.rs
- contracts/feature-tests/basic-features/src/macros.rs
- contracts/feature-tests/basic-features/tests/basic_features_test.rs
- contracts/feature-tests/use-module/src/use_module.rs
- contracts/modules/elrond-wasm-module-bonding-curve/src/utils/owner_endpoints.rs
- contracts/modules/elrond-wasm-module-bonding-curve/src/utils/user_endpoints.rs
- contracts/modules/elrond-wasm-module-features/src/lib.rs
- elrond-wasm-derive/src/preprocessing.rs
- elrond-wasm/src/contract_base/contract_base_trait.rs
- elrond-wasm/src/contract_base/wrappers/error_helper.rs
- elrond-wasm/src/contract_base/wrappers/mod.rs
- elrond-wasm/src/hex_call_data/cd_de.rs
- elrond-wasm/src/macros.rs
- elrond-wasm/src/types/io/mod.rs
- elrond-wasm/src/types/io/sc_error.rs
- elrond-wasm/src/types/io/sc_error_managed.rs
- elrond-wasm/src/types/io/sc_error_static.rs
- elrond-wasm/src/types/io/sc_result.rs
SC errors no longer keep their data on the heap!
> SC Error Optimization - static vs. managed

- contracts/examples/multisig/src/multisig.rs
- contracts/examples/ping-pong-egld/src/ping_pong.rs
- contracts/feature-tests/basic-features/src/storage_mapper_map_storage.rs
- elrond-codec/src/lib.rs
- elrond-codec/src/try_static_cast.rs
- elrond-wasm/src/storage/mappers/user_mapper.rs
- elrond-wasm/src/types/managed/managed_multi_result_vec.rs
The user mapper was still not migrated to the new model.
> User mapper uses managed addresses

- contracts/feature-tests/composability/mandos/forw_raw_transf_exec_egld.scen.json
- contracts/feature-tests/composability/vault/src/vault.rs
Added test in forwarder for direct_egld_execute
> Transfer Egld Exec test

- contracts/examples/erc1155-marketplace/src/lib.rs
- contracts/examples/erc1155/src/erc1155.rs
- contracts/feature-tests/basic-features/src/blockchain_api_features.rs
- elrond-wasm-debug/src/api/blockchain_api_mock.rs
- elrond-wasm-node/src/api/blockchain_api_node.rs
- elrond-wasm-node/src/api/managed_types/managed_buffer_api_node.rs
- elrond-wasm-node/src/api/managed_types/mod.rs
- elrond-wasm-node/src/api/send_api_node_legacy.rs
- elrond-wasm/src/api/blockchain_api.rs
- elrond-wasm/src/api/uncallable/blockchain_api_uncallable.rs
- elrond-wasm/src/contract_base/wrappers/blockchain_wrapper.rs
- is_smart_contract
- get_balance
- get_shard_of_address
> blockchain API - last missing managed methods

- contracts/examples/crypto-kitties/kitty-genetic-alg/src/lib.rs
- contracts/examples/crypto-kitties/kitty-ownership/src/lib.rs
- contracts/examples/lottery-erc20/src/lottery.rs
- contracts/examples/lottery-esdt/src/lottery.rs
- contracts/feature-tests/basic-features/src/block_info_features.rs
- contracts/feature-tests/basic-features/src/blockchain_api_features.rs
- elrond-wasm-debug/src/api/blockchain_api_mock.rs
- elrond-wasm-debug/src/api/send_api_mock.rs
- elrond-wasm-node/src/api/blockchain_api_node.rs
- elrond-wasm-node/src/api/send_api_node_legacy.rs
- elrond-wasm-node/src/api/send_api_node_managed.rs
- elrond-wasm/src/api/blockchain_api.rs
- elrond-wasm/src/api/uncallable/blockchain_api_uncallable.rs
- elrond-wasm/src/contract_base/wrappers/blockchain_wrapper.rs
- elrond-wasm/src/types/interaction/callback_closure.rs
Renamed methods for consistency.
> bloackchain api - method rename

- contracts/examples/crypto-kitties/kitty-auction/src/auction.rs
- contracts/examples/crypto-kitties/kitty-auction/src/lib.rs
- contracts/examples/crypto-kitties/kitty-ownership/src/lib.rs
- contracts/examples/erc1155-marketplace/src/lib.rs
- contracts/examples/erc1155/src/erc1155.rs
- contracts/examples/order-book/pair/src/validation.rs
- contracts/feature-tests/basic-features/src/basic_features_main.rs
- contracts/feature-tests/basic-features/src/managed_buffer_features.rs
- contracts/feature-tests/basic-features/src/token_identifier_features.rs
- contracts/feature-tests/basic-features/tests/basic_features_managed_buffer_test.rs
- contracts/feature-tests/basic-features/tests/basic_features_token_identifier_test.rs
- contracts/feature-tests/composability/proxy-test-first/src/proxy-test-first.rs
- elrond-wasm-debug/tests/sample_adder.rs
- elrond-wasm-derive/src/generate/snippets.rs
- elrond-wasm-derive/src/preprocessing/substitution_list.rs
- elrond-wasm/src/contract_base/wrappers/managed_type_helper.rs
- elrond-wasm/src/storage/mappers/user_mapper.rs
- elrond-wasm/src/types/general/token_identifier.rs
- elrond-wasm/src/types/interaction/contract_deploy.rs
- elrond-wasm/src/types/managed/managed_address.rs
- elrond-wasm/src/types/managed/managed_conversion.rs
`TokenIdentifier::egld`
`TokenIdentifier::from`
`ManagedAddress::zero`
`ManagedAddress::from`
> More substitutions - TokenIdentifier, ManagedAddress

- contracts/benchmarks/send-tx-repeat/tests/mandos_rs_test.rs
- contracts/benchmarks/str-repeat/tests/mandos_rs_test.rs
- contracts/examples/adder/tests/mandos_rs_test.rs
- contracts/examples/crowdfunding-erc20/tests/crowdfunding_erc20_mandos_rs_test.rs
- contracts/examples/crowdfunding-esdt/tests/crowdfunding_esdt_mandos_rs_test.rs
- contracts/examples/crypto-bubbles/tests/crypto_bubbles_mandos_rs_test.rs
- contracts/examples/crypto-kitties/kitty-auction/tests/kitty_auction_mandos_rs_test.rs
- contracts/examples/crypto-kitties/kitty-genetic-alg/tests/kitty_genetic_alg_mandos_rs_test.rs
- contracts/examples/crypto-kitties/kitty-ownership/tests/kitty_ownership_mandos_rs_test.rs
- contracts/examples/egld-esdt-swap/tests/egld_esdt_swap_mandos_rs_test.rs
- contracts/examples/erc1155-marketplace/tests/erc1155_marketplace_mandos_rs_test.rs
- contracts/examples/erc1155/tests/erc1155_mandos_rs_test.rs
- contracts/examples/erc20/tests/mandos_rs_test.rs
- contracts/examples/erc721/tests/nft_mandos_rs_test.rs
- contracts/examples/lottery-erc20/tests/lottery_erc20_mandos_rs_test.rs
- contracts/examples/lottery-esdt/tests/lottery_esdt_mandos_rs_test.rs
- contracts/examples/multisig/tests/multisig_mandos_rs_test.rs
- contracts/examples/ping-pong-egld/tests/ping_pong_egld_mandos_rs_test.rs
- contracts/feature-tests/basic-features/tests/basic_features_mandos_rs_test.rs
- contracts/feature-tests/composability/esdt-contract-pair/tests/mandos_rs_test.rs
- contracts/feature-tests/composability/tests/composability_mandos_rs_test.rs
- contracts/feature-tests/panic-message-features/tests/mandos_rs_test.rs
- contracts/feature-tests/payable-features/tests/mandos_go_test.rs
- contracts/feature-tests/payable-features/tests/mandos_rs_test.rs
- contracts/feature-tests/payable-features/tests/payable_features_mandos.rs
- contracts/feature-tests/use-module/tests/use_module_mandos_rs_test.rs
- elrond-wasm-debug/src/execute_mandos.rs
- elrond-wasm-debug/tests/framework_mandos_test.rs
- elrond-wasm-debug/tests/sample_adder.rs
- tools/test-gen/src/test_gen.rs
Very very minor refactor.
Meant to help reduce the size of another PR.
> debug refactor - contract map reference

- contracts/feature-tests/composability/mandos/forwarder_call_sync_accept_multi_transfer.scen.json
- contracts/feature-tests/composability/tests/composability_mandos_go_test.rs
- contracts/feature-tests/composability/tests/composability_mandos_rs_test.rs
- contracts/feature-tests/composability/vault/src/vault.rs
- elrond-wasm-debug/src/api/send_api_mock.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/builtin_func_exec.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/esdt_multi_transfer_mock.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/esdt_nft_transfer_mock.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/esdt_transfer_mock.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/mod.rs
- elrond-wasm-debug/tests/mandos/esdt-zero-balance-check-err.scen.json
- elrond-wasm/src/api/mod.rs
- elrond-wasm/src/api/send_api.rs
- elrond-wasm/src/types/interaction/contract_call.rs
- mandos/src/model/esdt_data/esdt_data_check.rs
- mandos/src/model/value/value_basic.rs
- mandos/src/model/value/value_check.rs
- mandos/src/serde_raw/esdt_data_raw/esdt_data_raw_check.rs
- mandos/src/serde_raw/esdt_data_raw/esdt_full_raw.rs
- ESDTNFTTransfer
- MultiESDTNFTTransfer
- execute_on_dest_context_raw_custom_result_range
> elrond-wasm-debug refactor #5

- contracts/examples/multisig/src/multisig.rs
- contracts/examples/multisig/src/multisig_propose.rs
- contracts/examples/multisig/src/multisig_state.rs
Change `action_signer_ids` storage type to SetMapper
> Multisig storage

- elrond-wasm-debug/tests/derive_managed_vec_item_biguint_test.rs
- elrond-wasm-debug/tests/derive_managed_vec_item_esdt_token_payment_test.rs
- elrond-wasm-debug/tests/derive_managed_vec_item_numbers_test.rs
- elrond-wasm-debug/tests/managed_vec_test.rs
- elrond-wasm-derive/src/managed_vec_item_derive.rs
- elrond-wasm/src/contract_base/wrappers/managed_type_helper.rs
- elrond-wasm/src/types/general/esdt_local_role.rs
- elrond-wasm/src/types/general/esdt_token_payment.rs
- elrond-wasm/src/types/general/esdt_token_payment_multi_arg.rs
- elrond-wasm/src/types/managed/managed_multi_result_vec.rs
- elrond-wasm/src/types/managed/managed_multi_result_vec_counted.rs
- elrond-wasm/src/types/managed/managed_multi_result_vec_eager.rs
- elrond-wasm/src/types/managed/managed_vec.rs
- elrond-wasm/src/types/managed/managed_vec_item.rs
- elrond-wasm/src/types/managed/managed_vec_iter.rs
`ManagedVecItem` cleanup only.
> Managed types static API (part 2)

- contracts/feature-tests/basic-features/mandos/managed_address_array.scen.json
- contracts/feature-tests/basic-features/mandos/managed_address_managed_buffer.scen.json
- contracts/feature-tests/basic-features/src/basic_features_main.rs
- contracts/feature-tests/basic-features/src/managed_address_features.rs
- contracts/feature-tests/basic-features/tests/basic_features_mandos_go_test.rs
- contracts/feature-tests/basic-features/tests/basic_features_mandos_rs_test.rs
- elrond-wasm/src/types/managed/managed_address.rs
- elrond-wasm/src/types/managed/managed_byte_array.rs
- add `ManagedAddress::as_managed_buffer`
- add `try_from` for `ManagedAddress` (from `ManagedBuffer`)
- add tests
> Add `ManagedAddress::as_managed_buffer`

- contracts/examples/crowdfunding-esdt/tests/crowdfunding_esdt_rust_test.rs
- contracts/examples/empty/tests/empty_rust_test.rs
- contracts/feature-tests/rust-testing-framework-tester/src/lib.rs
- contracts/feature-tests/rust-testing-framework-tester/tests/rust_testing_framework-test.rs
- elrond-wasm-debug/src/testing_framework/contract_obj_wrapper.rs
- adding the option of creating accounts with a fixed address instead of generating one
- removed StateChange. Changes are now automatically commited/reverted based on the TxResult.
> Testing framework improvements

- contracts/examples/nft-minter/src/lib.rs
- contracts/examples/nft-minter/src/nft_module.rs
- contracts/examples/nft-minter/wasm/src/lib.rs
- add function to claim royalties from marketplace
- remove SCResults()
- remove #payment annotations
> nft minter claim royalties

- contracts/feature-tests/composability/forwarder-raw/src/forwarder_raw.rs
- contracts/feature-tests/composability/forwarder-raw/wasm-no-managed-ei/src/lib.rs
- contracts/feature-tests/composability/forwarder-raw/wasm/src/lib.rs
- contracts/feature-tests/composability/mandos/forw_raw_direct_multi_esdt.scen.json
- contracts/feature-tests/composability/tests/composability_mandos_go_test.rs
- contracts/feature-tests/composability/tests/composability_mandos_rs_test.rs
- elrond-wasm/src/contract_base/wrappers/send_wrapper.rs
New `self.send().direct_multi()` function, for convenience.
> Direct multi

- contracts/feature-tests/use-module/Cargo.toml
- contracts/feature-tests/use-module/use_module_expected_main.abi.json
- elrond-wasm-modules/src/dns.rs
- elrond-wasm-modules/src/features.rs
- elrond-wasm-modules/src/pause.rs
- elrond-wasm-modules/src/users.rs
- elrond-wasm/src/types/managed/big_int.rs
- elrond-wasm/src/types/managed/big_uint.rs
- elrond-wasm/src/types/managed/managed_buffer.rs
- elrond-wasm/src/types/managed/managed_buffer_cached_builder.rs
- elrond-wasm/src/types/managed/managed_byte_array.rs
- elrond-wasm/src/types/managed_codec/managed_buffer_nested_en_output.rs
Also simplified the specialized nested encode.
> Modules cleanup & remove allocator

- contracts/feature-tests/abi-tester/abi_tester_expected_main.abi.json
- contracts/feature-tests/abi-tester/abi_tester_expected_view.abi.json
- contracts/feature-tests/use-module/use_module_expected_main.abi.json
- contracts/feature-tests/use-module/use_module_expected_view.abi.json
- elrond-wasm-debug/src/abi_json/build_info_abi_json.rs
- elrond-wasm-debug/src/abi_json/mod.rs
- elrond-wasm-derive/src/generate/abi_gen.rs
- elrond-wasm/Cargo.toml
- elrond-wasm/src/abi/build_info_abi.rs
- elrond-wasm/src/abi/mod.rs
Git tag/last commit info in ABI.
> abi git version

- contracts/examples/crypto-kitties/kitty-auction/Cargo.toml
- contracts/examples/crypto-kitties/kitty-ownership/Cargo.toml
- contracts/examples/egld-esdt-swap/Cargo.toml
- contracts/examples/nft-minter/Cargo.toml
- contracts/examples/nft-minter/src/nft_module.rs
- contracts/feature-tests/composability/forwarder-raw/Cargo.toml
- contracts/feature-tests/composability/forwarder/Cargo.toml
- contracts/feature-tests/composability/proxy-test-first/Cargo.toml
- contracts/feature-tests/composability/recursive-caller/Cargo.toml
- contracts/feature-tests/erc-style-contracts/lottery-erc20/Cargo.toml
- contracts/feature-tests/use-module/Cargo.toml
- elrond-wasm/Cargo.toml
- elrond-wasm/src/types/interaction/mod.rs
feature `cb_closure_managed_deser` replaced with `cb_closure_unmanaged_deser`
> Callback closure managed decode feature flipped

- contracts/examples/nft-storage-prepay/src/nft_storage_prepay.rs
This decorator seems to be missing
> Fix missing decorator on claim method in example sc

- elrond-wasm/src/formatter/formatter_impl_bytes.rs
- elrond-wasm/src/formatter/formatter_impl_num.rs
- elrond-wasm/tests/formatter_test.rs
Hex implementation for (unsigned) int on 8, 16, 32, 64 bits.
> ATSDI-1477: extend formatter for hex

- Cargo.toml
- contracts/feature-tests/composability/Cargo.toml
- contracts/feature-tests/composability/forwarder-raw/src/forwarder_raw.rs
- contracts/feature-tests/composability/forwarder-raw/wasm-no-managed-ei/src/lib.rs
- contracts/feature-tests/composability/forwarder-raw/wasm/src/lib.rs
- contracts/feature-tests/composability/mandos/promises_multi_transfer.scen.json
- contracts/feature-tests/composability/mandos/promises_single_transfer.scen.json
- contracts/feature-tests/composability/promises-features/Cargo.toml
- contracts/feature-tests/composability/promises-features/elrond.json
- contracts/feature-tests/composability/promises-features/meta/Cargo.toml
- contracts/feature-tests/composability/promises-features/meta/src/main.rs
- contracts/feature-tests/composability/promises-features/src/promises_features.rs
- contracts/feature-tests/composability/promises-features/wasm/Cargo.toml
- contracts/feature-tests/composability/promises-features/wasm/src/lib.rs
- contracts/feature-tests/composability/tests/composability_mandos_go_test.rs
- contracts/feature-tests/composability/tests/composability_mandos_rs_test.rs
- elrond-wasm-node/src/api/send_api_node_impl_legacy.rs
- tools/test-gen/src/test_gen.rs
- vm-test-build-copy.sh
Functionality tests moved from forwarder-raw.
> promises-features contract

- elrond-wasm-debug/src/tx_execution/exec_contract_endpoint.rs
- elrond-wasm/src/contract_base/wrappers/send_wrapper.rs
- elrond-wasm/src/storage/mappers/non_fungible_token_mapper.rs
- also added a clippy allow (clippy is wrong in said instance)
> nft create named shortcut

- elrond-wasm/src/types/flags/code_metadata.rs
- elrond-wasm/tests/formatter_test.rs
Signed-off-by: Costin Carabaș <costin.carabas@gmail.com>
> Display Code Metadata

- elrond-wasm-debug/src/meta/meta_wasm_build.rs
- wat-build.sh
Employing the Wizard of `wasm-opt -Oz`
> wasm-opt optimize for size

- elrond-wasm-derive/src/format/format_parts.rs
Fix an issue where a format string of the form `test{}/{}.json` would have it's delimiter (the slash) omitted because it's exactly one character.
> Fix single char delimiter bug in format_parts

- contracts/examples/lottery-esdt/src/lottery.rs
Small improvements - reusing mapper objects where possible.
> lottery esdt improvements

- contracts/feature-tests/basic-features/mandos/big_num_conversions.scen.json
- contracts/feature-tests/basic-features/src/basic_features_main.rs
- contracts/feature-tests/basic-features/wasm/src/lib.rs
- elrond-wasm-derive/src/generate/method_gen.rs
- elrond-wasm-derive/src/model/argument.rs
- elrond-wasm-derive/src/parse/argument_parse.rs
Endpoints can now have arguments declared as mutable.
> mutable endpoint arg

- contracts/examples/lottery-esdt/src/lottery.rs
- elrond-wasm-debug/src/mandos_step/contract_call_mandos_attach.rs
- elrond-wasm-debug/tests/managed_option_test.rs
- elrond-wasm-debug/tests/sample_adder.rs
- elrond-wasm-derive/src/generate/snippets.rs
- elrond-wasm-derive/src/preprocessing/substitution_list.rs
- elrond-wasm/src/api/managed_types/const_handles.rs
- elrond-wasm/src/contract_base/proxy_obj_base.rs
- elrond-wasm/src/err_msg.rs
- elrond-wasm/src/types/interaction/contract_deploy.rs
- elrond-wasm/src/types/managed/basic/big_int.rs
- elrond-wasm/src/types/managed/mod.rs
- elrond-wasm/src/types/managed/wrapped/esdt_token_payment.rs
- elrond-wasm/src/types/managed/wrapped/managed_option.rs
- elrond-wasm/src/types/managed/wrapped/managed_ref.rs
- elrond-wasm/src/types/managed/wrapped/managed_vec.rs
- elrond-wasm/src/types/managed/wrapped/mod.rs
A very efficient optional managed type.
`None` is flagged by a special invalid handle.
> ManagedOption

- contracts/feature-tests/use-module/use_module_expected_main.abi.json
- elrond-wasm-modules/src/pause.rs
- use SingleValueMapper instead of old storage_set/storage_get
> updated pause module

- contracts/core/price-aggregator/src/events.rs
- contracts/core/price-aggregator/src/lib.rs
- elrond-codec/src/single/nested_de_input.rs
- elrond-codec/src/single/nested_de_input_owned.rs
- elrond-codec/src/single/nested_de_input_slice.rs
- elrond-wasm-debug/tests/esdt_token_payment_test.rs
- elrond-wasm-debug/tests/managed_vec_test.rs
- elrond-wasm/Cargo.toml
- elrond-wasm/src/types/managed/codec_util/managed_buffer_nested_de_input.rs
- elrond-wasm/src/types/managed/wrapped/esdt_token_payment.rs
Also needed a new `peek` method.
> EsdtTokenPayment legacy decode

- contracts/examples/nft-minter/src/nft_module.rs
- contracts/feature-tests/composability/vault/src/vault.rs
- elrond-codec/src/impl_for_types/impl_phantom.rs
- elrond-codec/src/multi/into_multi_value.rs
- elrond-codec/src/multi/mod.rs
- elrond-wasm-modules/src/bonding_curve/utils/owner_endpoints.rs
- elrond-wasm-modules/src/bonding_curve/utils/structs.rs
- elrond-wasm-modules/src/bonding_curve/utils/user_endpoints.rs
- elrond-wasm-modules/src/esdt.rs
- elrond-wasm-modules/src/ongoing_operation.rs
- elrond-wasm/src/macros.rs
- elrond-wasm/src/types/managed/wrapped/esdt_token_payment.rs
- elrond-wasm/src/types/managed/wrapped/managed_vec.rs
> IntoMultiValue trait

- contracts/examples/crypto-kitties/kitty-ownership/src/lib.rs
- contracts/feature-tests/use-module/wasm/src/lib.rs
- elrond-wasm-debug/src/mandos_system/mandos_rs_runner.rs
- elrond-wasm-debug/tests/sample_adder.rs
- elrond-wasm-derive/src/contract_impl.rs
- elrond-wasm-derive/src/generate/endpoints_mod_gen.rs
- elrond-wasm/src/contract_base/mod.rs
- elrond-wasm/src/contract_base/universal_contract_obj.rs
Also needed to perform a build fix and a cargo fmt.
> Endpoints monomorphization issue fix

- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/builtin_func_exec.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/builtin_func_map.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/builtin_func_role_check_wrapper.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/builtin_func_trait.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/change_owner_mock.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/claim_developer_rewards_mock.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/esdt_local_burn.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/esdt_local_mint.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/esdt_multi_transfer_mock.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/esdt_nft_add_quantity_mock.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/esdt_nft_add_uri_mock.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/esdt_nft_burn_mock.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/esdt_nft_create_mock.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/esdt_nft_transfer_mock.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/esdt_nft_update_attriutes_mock.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/esdt_transfer_mock.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/mod.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/set_username_mock.rs
- elrond-wasm-debug/src/tx_execution/builtin_function_mocks/upgrade_contract.rs
- elrond-wasm-debug/src/world_mock/blockchain_mock.rs
An old-school OOP polymorphic map is more flexible than just a match and some functions.
> builtin fuctions polymorphic map

- framework/meta/src/cli_args/meta_build_args.rs
- framework/meta/src/cli_args/meta_cli_args.rs
- framework/meta/src/cli_args/mod.rs
- framework/meta/src/generate_snippets/snippet_gen_main.rs
- framework/meta/src/lib.rs
- framework/meta/src/meta_abi.rs
- framework/meta/src/meta_config.rs
- framework/meta/src/meta_main.rs
- framework/meta/src/meta_wasm_tools.rs
- framework/meta/src/output_contract/output_contract_model.rs
- framework/meta/src/output_contract/output_contract_wasm_build.rs
Preliminary refactor before adding twiggy functionality.
Separated parsing of CLI arguments from the execution.
> meta CLI args refactor

- contracts/examples/digital-cash/tests/digital_cash_mandos_rs_test.rs
- contracts/examples/multisig/tests/multisig_mandos_go_test.rs
- contracts/feature-tests/alloc-features/tests/alloc_features_mandos_rs_test.rs
- contracts/feature-tests/basic-features/tests/basic_features_mandos_rs_test.rs
- contracts/feature-tests/big-float-features/tests/big_float_mandos_rs_test.rs
- contracts/feature-tests/composability/esdt-contract-pair/tests/mandos_go_test.rs
- contracts/feature-tests/composability/esdt-contract-pair/tests/mandos_rs_test.rs
- contracts/feature-tests/composability/tests/composability_mandos_go_test.rs
- contracts/feature-tests/composability/tests/composability_mandos_rs_test.rs
- contracts/feature-tests/erc-style-contracts/lottery-erc20/tests/lottery_erc20_mandos_go_test.rs
- contracts/feature-tests/erc-style-contracts/lottery-erc20/tests/lottery_erc20_mandos_rs_test.rs
Figured out this neat trick a while ago.
Better not have commented tests, or commented code in general.
> tests ignored instead of commented out

- contracts/modules/src/token_merge/readme.md
Create readme.md for NFTs owning NFTs
> Create readme.md for NFTs owning NFTs

- framework/scenario/Cargo.toml
- framework/scenario/src/lib.rs
- framework/scenario/src/main.rs
- framework/scenario/src/standalone/account_tool.rs
- framework/scenario/src/standalone/mod.rs
- framework/scenario/src/standalone/scenario_cli.rs
- framework/snippets/src/interactor_result.rs
- sdk/core/examples/account_storage.rs
- sdk/core/src/blockchain.rs
- sdk/core/src/data/account.rs
- sdk/core/src/data/account_storage.rs
- sdk/core/src/data/mod.rs
- sdk/scenario-format/src/serde_raw/esdt_data_raw/esdt_full_raw.rs
- sdk/scenario-format/src/serde_raw/esdt_data_raw/instance_raw.rs
To try out:
```
cd framework/scenario
cargo run account --api https://testnet-gateway.multiversx.com --address erd1qqqqqqqqqqqqqpgq807np9ye33s94nfa5wsrkttmssy3hr2hd8ss3398h2
```
Outputs to console:
```
{
"steps": [
{
"step": "setState",
"accounts": {
"sc:erd1qqqqqqqqqqqqqpgq807np9ye33s94nfa5wsrkttmssy3hr2hd8ss3398h2": {
"nonce": "0",
"balance": "0",
"esdt": {
"TESTCOLL1-74d4ae": {
"instances": [
{
"nonce": "1",
"balance": "1"
},
{
"nonce": "3",
"balance": "1"
},
{
"nonce": "2",
"balance": "1"
}
]
}
},
"username": "",
"storage": {
"0x454c524f4e446573647454455354434f4c4c312d37346434616501": "0x080112020001",
"0x454c524f4e446573647454455354434f4c4c312d37346434616502": "0x080112020001",
"0x454c524f4e446573647454455354434f4c4c312d37346434616503": "0x080112020001", …
```
> Tool to create scenario from real account storage

- contracts/examples/multisig/interact-rs/.gitignore
- contracts/examples/multisig/interact-rs/Cargo.toml
- contracts/examples/multisig/interact-rs/config.toml
- contracts/examples/multisig/interact-rs/src/multisig_interact.rs
- contracts/examples/multisig/interact-rs/src/multisig_interact_config.rs
- contracts/examples/multisig/interact-rs/src/multisig_interact_nfts.rs
- contracts/examples/multisig/interact-rs/src/multisig_interact_state.rs
> State and Config for MultisigInteract

- contracts/feature-tests/composability/interact/.gitignore
- contracts/feature-tests/composability/interact/Cargo.toml
- contracts/feature-tests/composability/interact/config.toml
- contracts/feature-tests/composability/interact/src/composability_interact.rs
- contracts/feature-tests/composability/interact/src/composability_interact_config.rs
- contracts/feature-tests/composability/interact/src/composability_interact_state.rs
Split State logic in state and config
> Composability interactor refactor

- contracts/feature-tests/composability/forwarder-queue/Cargo.toml
- contracts/feature-tests/composability/forwarder-queue/scenarios/forw_raw_async_accept_egld.scen.json
- contracts/feature-tests/composability/forwarder-queue/src/forwarder_queue.rs
- contracts/feature-tests/composability/forwarder-queue/wasm/Cargo.lock
- contracts/feature-tests/composability/scenarios/forw_queue_async.scen.json
- contracts/feature-tests/composability/tests/composability_scenario_go_test.rs
- contracts/feature-tests/composability/tests/composability_scenario_rs_test.rs
Create multiple async calls via forwarder
> Add scenario for forwarder-queue

- .github/workflows/actions.yml
- contracts/benchmarks/send-tx-repeat/Cargo.toml
- contracts/examples/order-book/pair/Cargo.toml
- contracts/feature-tests/erc-style-contracts/erc1155-user-mock/Cargo.toml
- contracts/feature-tests/erc-style-contracts/erc1155-user-mock/src/lib.rs
- contracts/feature-tests/erc-style-contracts/erc1155/Cargo.toml
- contracts/feature-tests/use-module/Cargo.toml
Some of the allocs were unnecessary.
This is helpful later on.
> removed unnecessary alloc feature flags

- contracts/feature-tests/composability/tests/composability_scenario_go_test.rs
- contracts/feature-tests/composability/vault/src/vault.rs
A few tests had to be ignored.
> vault contract uses transfer-exec to return funds

- contracts/examples/digital-cash/src/digital_cash.rs
- contracts/feature-tests/basic-features/scenarios/crypto_verify_ed25519.scen.json
- contracts/feature-tests/basic-features/src/crypto_features.rs
- framework/base/src/api/crypto_api.rs
- framework/base/src/api/uncallable/crypto_api_uncallable.rs
- framework/base/src/contract_base/wrappers/crypto_wrapper.rs
- framework/wasm-adapter/src/api/crypto_api_node.rs
- vm/src/api/crypto_api_mock.rs
The API was not matching VM behavior.
We also had no test for failure.
> verify ed25519 api fix

- framework/meta/src/cmd/standalone/all.rs
- framework/meta/src/print_util.rs
> meta all command pretty print current index

- contracts/feature-tests/alloc-features/tests/alloc_features_scenario_rs_test.rs
- framework/base/src/api/external_view/ev_storage_api.rs
- framework/base/src/api/storage_api.rs
- framework/base/src/api/uncallable/storage_api_uncallable.rs
- framework/base/src/storage/storage_get.rs
- framework/base/src/storage/storage_get_from_address.rs
- framework/scenario/src/api/managed_type_api_vh/managed_buffer_api_vh.rs
- framework/scenario/src/api/storage_api_vh.rs
- framework/wasm-adapter/src/api/storage_api_node.rs
- vm/src/api/storage_api_mock.rs
- vm/src/vm_hooks/vh_handler/vh_storage.rs
This time the `alloc-features` contract tests also pass.
> DebuggerApi bugfix & storage cleanup

- contracts/feature-tests/composability/tests/composability_scenario_rs_test.rs
- framework/base/src/api/managed_types/big_int_api.rs
- framework/base/src/api/uncallable/big_int_api_uncallable.rs
- framework/scenario/src/api.rs
- framework/scenario/src/api/blockchain_api_vh.rs
- framework/scenario/src/api/managed_type_api_vh/big_int_api_vh.rs
- framework/scenario/src/api/send_api_vh.rs
- framework/wasm-adapter/src/api/managed_types/big_int_api_node.rs
- vm/src/api/managed_types/big_int_api_mock.rs
- vm/src/vm_hooks/vh_debugger_stack.rs
- vm/src/vm_hooks/vh_dispatcher.rs
- vm/src/vm_hooks/vh_handler.rs
- vm/src/vm_hooks/vh_handler/vh_send.rs
- vm/src/vm_hooks/vh_managed_types_cell.rs
- vm/src/vm_hooks/vh_source.rs
All composability tests now pass.
> DebuggerApi - SendApi implementation

- contracts/feature-tests/rust-testing-framework-tester/tests/rust_mandos_v1_test.rs
- framework/base/src/err_msg.rs
- framework/scenario/src/api/impl_vh/debug_api.rs
- framework/scenario/src/api/impl_vh/debug_handle_vh.rs
- framework/scenario/src/whitebox/contract_obj_wrapper.rs
- vm/src/tx_execution/catch_tx_panic.rs
- vm/src/tx_execution/exec_contract_endpoint.rs
- vm/src/tx_execution/mod.rs
- vm/src/tx_mock/tx_context_ref.rs
- vm/src/tx_mock/tx_panic.rs
- vm/src/vm_hooks/vh_debugger_stack.rs
- vm/src/vm_hooks/vh_handler/vh_call_value.rs
- vm/src/vm_hooks/vh_handler/vh_crypto.rs
- vm/src/vm_hooks/vh_handler/vh_endpoint_arg.rs
- vm/src/vm_hooks/vh_handler/vh_error.rs
- vm/src/vm_hooks/vh_handler/vh_managed_types/vh_big_float.rs
- vm/src/vm_hooks/vh_handler/vh_managed_types/vh_big_int.rs
- vm/src/vm_hooks/vh_source.rs
- vm/src/world_mock/account_data.rs
I tried to clean up the panic/catch system.
The purpose is to use BreakpointValue to interrupt execution in the executor, but some refactoring is required first. This is the first part.
> VM - error handling refactoring #1

- vm/src/tx_execution/builtin_function_mocks/builtin_func_container.rs
- vm/src/tx_execution/builtin_function_mocks/builtin_func_trait.rs
- vm/src/tx_execution/builtin_function_mocks/esdt_nft/esdt_local_burn.rs
- vm/src/tx_execution/builtin_function_mocks/esdt_nft/esdt_local_mint.rs
- vm/src/tx_execution/builtin_function_mocks/esdt_nft/esdt_nft_add_quantity_mock.rs
- vm/src/tx_execution/builtin_function_mocks/esdt_nft/esdt_nft_add_uri_mock.rs
- vm/src/tx_execution/builtin_function_mocks/esdt_nft/esdt_nft_burn_mock.rs
- vm/src/tx_execution/builtin_function_mocks/esdt_nft/esdt_nft_create_mock.rs
- vm/src/tx_execution/builtin_function_mocks/esdt_nft/esdt_nft_update_attriutes_mock.rs
- vm/src/tx_execution/builtin_function_mocks/general/change_owner_mock.rs
- vm/src/tx_execution/builtin_function_mocks/general/claim_developer_rewards_mock.rs
- vm/src/tx_execution/builtin_function_mocks/general/migrate_username_mock.rs
- vm/src/tx_execution/builtin_function_mocks/general/set_username_mock.rs
- vm/src/tx_execution/builtin_function_mocks/general/upgrade_contract.rs
- vm/src/tx_execution/builtin_function_mocks/transfer/esdt_multi_transfer_mock.rs
- vm/src/tx_execution/builtin_function_mocks/transfer/esdt_nft_transfer_mock.rs
- vm/src/tx_execution/builtin_function_mocks/transfer/esdt_transfer_mock.rs
Some additional cleanup in the BuiltinFunction trait. I felt it would have been to much noise to add it to the first builtin functions refactor PR.
> VM refactor: builtin functions #2

- contracts/examples/adder/tests/adder_test.rs
- framework/base/src/storage/storage_key.rs
- framework/scenario/src/api.rs
- framework/scenario/src/api/impl_vh.rs
- framework/scenario/src/api/impl_vh/debug_api.rs
- framework/scenario/src/api/impl_vh/single_tx_api.rs
- framework/scenario/src/api/impl_vh/static_api.rs
- framework/scenario/tests/contract_without_macros.rs
- framework/scenario/tests/single_tx_api_test.rs
- framework/scenario/tests/test_hash_bi_di_mapper.rs
- framework/scenario/tests/test_hash_map_mapper.rs
- framework/scenario/tests/test_hash_map_storage_mapper.rs
- framework/scenario/tests/test_hash_set_mapper.rs
- framework/scenario/tests/test_hash_unordered_set_mapper.rs
- framework/scenario/tests/test_linked_list_mapper.rs
- framework/scenario/tests/test_queue_mapper.rs
- framework/scenario/tests/test_vec_mapper.rs
- vm/src/vm_hooks.rs
- vm/src/vm_hooks/vh_impl.rs
- vm/src/vm_hooks/vh_impl/vh_debug_api.rs
- vm/src/vm_hooks/vh_impl/vh_single_tx_api.rs
- vm/src/vm_hooks/vh_impl/vh_static_api.rs
- vm/src/world_mock/account_data.rs
A new API for unit tests, this one also accepts storage manipulation and others.
> SingleTxApi

- framework/scenario/src/scenario/model/step/typed_sc_query.rs
Minor refactor, the TypedScQuery had a different implementation from the rest.
> TypedScQuery refactor

- contracts/examples/adder/tests/adder_mandos_constructed_raw_test.rs
- contracts/examples/adder/tests/adder_mandos_constructed_with_calls_test.rs
- contracts/examples/crowdfunding-esdt/tests/crowdfunding_esdt_mandos_rust_test.rs
- contracts/examples/multisig/tests/multisig_rust_test_v2.rs
- framework/scenario/src/facade.rs
- framework/scenario/src/facade/scenario_world_steps.rs
- framework/scenario/src/facade/scenario_world_steps_deprecated.rs
Now the method names on the testing and the interactor frameworks are the same.
> testing framework - renamed step methods

- framework/scenario/src/scenario/model/transaction/tx_call.rs
I just changed the field gas_limit of the resulting contract_call in the to_contract_call function
> added gas limit information in the TxCall -> ContractCallWithEgld conversion

- framework/meta/Cargo.toml
- framework/meta/src/cli_args/cli_args_build.rs
`sc-meta all build --locked` was not working.
> meta all command - fixed --locked argument

- .github/workflows/release-upload.yml
- .github/workflows/template-test-current.yml
- .github/workflows/template-test-released.yml
- contracts/examples/ping-pong-egld/README.md
- contracts/examples/ping-pong-egld/mxsc-template.toml
- framework/meta/src/template/template_adjuster.rs
- framework/meta/tests/template_test.rs
- Register contract as a template: "ping-pong-egld".
- Cleanup within GitHub workflows (`libtinfo` not necessary)
> Add template for "ping-pong"

- contracts/feature-tests/abi-tester/tests/abi_tester_abi_test.rs
- framework/base/src/abi/contract_abi.rs
- framework/base/src/abi/endpoint_abi.rs
- framework/base/src/abi/esdt_attribute_abi.rs
- framework/base/src/abi/event_abi.rs
- framework/base/src/abi/type_abi.rs
- framework/base/src/abi/type_description.rs
- framework/base/src/external_view_contract.rs
- framework/base/src/types/io/operation_completion_status.rs
- framework/derive/src/generate/abi_gen.rs
- framework/derive/src/type_abi_derive.rs
- framework/meta/src/abi_json/build_info_abi_json.rs
- framework/meta/src/abi_json/contract_abi_json.rs
- framework/meta/src/abi_json/endpoint_abi_json.rs
- framework/meta/src/abi_json/esdt_attribute_abi_json.rs
- framework/meta/src/abi_json/event_abi_json.rs
- framework/meta/src/abi_json/type_abi_json.rs
- framework/meta/src/cmd/contract/generate_snippets/snippet_sc_functions_gen.rs
- framework/meta/src/cmd/contract/sc_config/oc_builder.rs
- framework/meta/src/cmd/contract/sc_config/oc_validate.rs
- ABI decode defaults fix
- type desciption from json
- removed static fields from ABI objects
> Enable ABI deserialization

- contracts/core/price-aggregator/src/lib.rs
- contracts/core/price-aggregator/tests/price_aggregator_blackbox_test.rs
- contracts/core/price-aggregator/tests/price_aggregator_whitebox_test.rs
- contracts/examples/check-pause/src/check_pause.rs
- contracts/feature-tests/alloc-features/src/macro_features_legacy.rs
- contracts/feature-tests/alloc-features/tests/alloc_features_general_test.rs
- contracts/feature-tests/basic-features/src/storage_mapper_map_storage.rs
- contracts/feature-tests/basic-features/src/storage_mapper_queue.rs
- contracts/feature-tests/use-module/src/use_module.rs
- framework/base/src/macros.rs
- framework/base/src/types/io/sc_result.rs
- framework/scenario/tests/contract_without_macros.rs
In fairness, it should have been deprecated for the past 2 years (0.27.0 could have been the deprecation release). I don't think anybody is using it anymore, this is really old news.
> deprecated SCResult

- framework/scenario/src/facade/world_tx/expr/file_expr.rs
- framework/scenario/src/facade/world_tx/expr/mxsc_expr.rs
- framework/scenario/src/facade/world_tx/scenario_env.rs
- framework/scenario/src/facade/world_tx/scenario_rh_list.rs
- framework/scenario/src/facade/world_tx/scenario_rh_list_item.rs
- framework/scenario/src/facade/world_tx/scenario_tx.rs
- framework/scenario/src/facade/world_tx/with_tx_raw_response.rs
Preliminary refactor, in preparation for the next PRs.
> unified syntax - scenario result handler generic env

- contracts/examples/adder/tests/adder_blackbox_test.rs
- framework/base/src/types/interaction/expr/sc_expr.rs
- framework/scenario/src/facade/expr/bech32_address.rs
- framework/scenario/src/facade/result_handlers.rs
- framework/scenario/src/facade/result_handlers/expect_value.rs
- framework/scenario/src/scenario/model/value/address_value.rs
> unified syntax - expect value

- Cargo.lock
- data/codec-derive/Cargo.toml
- data/codec/Cargo.toml
- framework/base/Cargo.toml
- framework/base/src/types/interaction/tx_data/tx_code_source.rs
- framework/base/src/types/interaction/tx_from.rs
- framework/base/src/types/interaction/tx_gas.rs
- framework/base/src/types/interaction/tx_payment.rs
- framework/base/src/types/interaction/tx_result_handler_list/tx_result_handler_list_item.rs
- framework/base/src/types/interaction/tx_to.rs
- framework/derive/Cargo.toml
- framework/meta-lib/Cargo.toml
- framework/scenario/Cargo.toml
- sdk/core/Cargo.toml
- vm/Cargo.toml
> Reintroduced diagnostic::on_unimplemented & rustc 1.78 dependency

- contracts/feature-tests/basic-features/scenarios/echo_varags_vec_with_counted.scen.json
- contracts/feature-tests/basic-features/scenarios/echo_varags_vec_with_counted_pairs.scen.json
- contracts/feature-tests/basic-features/src/echo_managed.rs
- contracts/feature-tests/basic-features/tests/basic_features_scenario_go_test.rs
- contracts/feature-tests/basic-features/tests/basic_features_scenario_rs_test.rs
- framework/base/src/types/managed/multi_value/mod.rs
- framework/base/src/types/managed/multi_value/multi_value_encoded_counted.rs
- framework/base/src/types/managed/multi_value/multi_value_encoded_iter.rs
- framework/derive/src/preprocessing/substitution_list.rs
Similar to `MultiValueManagedVec`, but lazy like `MultiValueEncoded`
> MultiValueEncodedCounted

- tools/rust-debugger/pretty-printers/multiversx_sc_lldb_pretty_printers.py
Version comment, to make it easier to figure out what version was installed.
> debugger scripts version comment

- .github/workflows/lldb-formatter-tests.yml
- framework/meta/src/cmd/install/install_debugger.rs
- tools/rust-debugger/format-tests/tests/run_format_tests.rs
- lldb debugger extension version handling on install / update
- bugfixing lldb preety printer not starting caused by rust regex rule change overwriting priorities
> lldb debugger bugfix
