.gitignore
elrond-wasm-derive/src/contract_gen_callback.rs
elrond-wasm-derive/src/contract_gen_finish.rs

This PR adds the same kind of return-type handling to derived SC callbacks that are added to SC methods.

Add return-type handling to callbacks as well

---

elrond-wasm/src/io/arg_loader_endpoint.rs
elrond-wasm/src/io/finish.rs

Add cases for `BigInt` to `load_single_arg()` and to `EndpointResult::finish()`.

Add handling for BigInts for autoarguments and finishing

---

build-wasm.sh

This update allows us to pass a `RUSTFLAGS` value to the build script without it being overridden. It defaults to the same value as before, which is that for an optimized build.

Make build script parametric

---

examples/adder/Cargo.toml
examples/adder/wasm/Cargo.toml
examples/adder/wasm/src/lib.rs
examples/crypto-bubbles/Cargo.toml
examples/crypto-bubbles/wasm/Cargo.toml
examples/crypto-bubbles/wasm/src/lib.rs
examples/factorial/Cargo.toml
examples/factorial/wasm/Cargo.toml
examples/factorial/wasm/src/lib.rs
examples/simple-erc20/Cargo.toml
examples/simple-erc20/wasm/Cargo.toml
examples/simple-erc20/wasm/src/lib.rs

Make minor adjustments to all the contracts in `examples`, to improve their usage as templates for `erdpy contract new`.

Adjust examples (for erdpy templates)

---

elrond-wasm-debug/src/ext_mock.rs
elrond-wasm-output/Cargo.toml
elrond-wasm-output/src/lib.rs
test-contracts/basic-features/mandos/panic.scen.json
test-contracts/basic-features/wasm/Cargo.toml

Panic messages are off by default. Can be activated in times of need.
This seems to help a lot with code size.

Wasm Shrink 3 

---

contracts/feature-tests/basic-features/Cargo.toml
elrond-wasm-node/Cargo.toml
elrond-wasm-node/src/ext.rs

The small-int-ei feature was introduced to help with compatibility before the Arwen version containing the new small int EI was released. Now that these endpoints are up, no more need to keep the feature flag.

Removed small-int-ei feature

---

contracts/feature-tests/basic-features/src/lib.rs
elrond-codec-derive/src/nested_de_derive.rs
elrond-codec-derive/src/nested_en_derive.rs
elrond-codec-derive/src/top_de_derive.rs
elrond-codec-derive/src/top_en_derive.rs
elrond-codec/Cargo.toml
elrond-codec/src/lib.rs
elrond-codec/tests/interference_test.rs
elrond-codec/tests/shadowing_test.rs
elrond-wasm-debug/src/blockchain_mock.rs
elrond-wasm-debug/src/execute_mandos.rs
elrond-wasm-debug/src/ext_mock.rs

The derive macro generation is immune to type shadowing,
i.e. any types that are in scope and happen to have the same name as elrond-codec types do not break the build.
The derive macro must generate fully qualified type names everywhere to avoid this hurdle.

elrond-codec-derive immune to type shadowing

---

contracts/examples/multisig/mandos/changeQuorum.scen.json
contracts/examples/multisig/mandos/deployAdder_then_call.scen.json
contracts/examples/multisig/mandos/deployFactorial.scen.json
contracts/examples/multisig/src/action.rs
contracts/examples/multisig/src/lib.rs
contracts/examples/multisig/src/user_role.rs
contracts/examples/ping-pong-egld/tests/mandos_test.rs

- explicit discardAction endpoint, unsign no longer removes actions automatically
- getPendingActionData view
- getPendingActionCount no longer needed, removed
- ample Rust/ABI docs

Multisig discardAction endpoint and other minor improvements

---

contracts/examples/ping-pong-egld/mandos/ping-pong-call-ping-after-deadline.scen.json
contracts/examples/ping-pong-egld/src/lib.rs
contracts/examples/ping-pong-egld/tests/mandos_test.rs

The ping-pong smart contract was designed with a user limit in mind. Because there's no user limit, but only a max funding limit, the user limit is enforced only if a user can't deposit after the deadline, after other users have withdrawn their sum (and hence the smart contract balance has decreased).

Add check for declining pings after the deadline

---

elrond-wasm-derive/src/contract_gen_method.rs

Without this, the `erdpy contract build` sometimes takes the warning into the `abi.json` and the build fails.

Output the payable warning on stderr

---

contracts/feature-tests/async/forwarder-raw/src/lib.rs
contracts/feature-tests/basic-features/src/lib.rs
elrond-wasm-debug/src/api/contract_api_mock.rs
elrond-wasm-derive/src/snippets.rs
elrond-wasm-node/src/api/contract_api_node.rs
elrond-wasm-node/src/api/send_api_node.rs
elrond-wasm/src/api/contract_api.rs
elrond-wasm/src/api/send_api.rs

- is_smart_contract
- get_shard_of_address
- a few more endpoints in the test contracts,
- removed calls to `transferESDT`

async call redesign - finishing touches

---

contracts/examples/ping-pong-egld/Cargo.toml
contracts/examples/ping-pong-egld/mandos/ping-pong-call-get-user-addresses.scen.json
contracts/examples/ping-pong-egld/mandos/ping-pong-call-ping-after-deadline.scen.json
contracts/examples/ping-pong-egld/mandos/ping-pong-call-ping-before-beginning.scen.json
contracts/examples/ping-pong-egld/mandos/ping-pong-call-ping-second-user.scen.json
contracts/examples/ping-pong-egld/mandos/ping-pong-call-ping-twice.scen.json
contracts/examples/ping-pong-egld/mandos/ping-pong-call-ping-wrong-ammount.scen.json
contracts/examples/ping-pong-egld/mandos/ping-pong-call-ping.scen.json
contracts/examples/ping-pong-egld/src/lib.rs
contracts/examples/ping-pong-egld/tests/mandos_test.rs

- add argument to ping in order to allow a payload (such as an ETH address) to be sent as transaction data; note that this argument is ignored in the smart contract code as it is meant to be viewed externally
- add get_user_addresses, for checking who the registered users are

Ping-pong v2

---

mandos/src/value_interpreter.rs
mandos/tests/interpreter_test.rs

`biguint:` only accepts positive numerical values, `nested:` accepts everything.

Mandos - `nested:` syntax fix

---

elrond-codec-derive/src/top_de_derive.rs
elrond-codec/tests/struct_or_default_generic_derive_test.rs
elrond-wasm/src/macros.rs

- fix deriving from TopEncodeOrDefault when using it for a struct with generic parameters (eg. MyStruct<BigUint>)
- add TopEncodeOrDefault, TopDecodeOrDefault to the derive_imports! macro

Fix TopDecodeOrDefault for generics, add tests

---

CHANGELOG.md
contracts/feature-tests/abi-tester/abi_test_expected.abi.json
elrond-wasm/src/abi/type_abi.rs

Syntax like `[Type; 5]` and `(Type1, Type2)` is too difficult to parse and too reminiscent of Rust.
New syntax: `array5<Type>`, `tuple2<Type1, Type2>`.

Simplified ABI tuple and array syntax

---

contracts/examples/egld-esdt-swap/src/lib.rs
contracts/examples/esdt-nft-marketplace/src/lib.rs
contracts/feature-tests/async/forwarder-raw/src/lib.rs
contracts/feature-tests/async/forwarder/src/lib.rs
contracts/feature-tests/esdt-contract-pair/first-contract/src/lib.rs
contracts/feature-tests/local-esdt-and-nft/src/lib.rs
elrond-wasm-debug/src/api/send_api_mock.rs
elrond-wasm-node/src/api/call_value_api_node.rs
elrond-wasm-node/src/api/send_api_node.rs
elrond-wasm/src/api/send_api.rs
elrond-wasm/src/types/interaction/transfer_egld_execute.rs
elrond-wasm/src/types/interaction/transfer_esdt_execute.rs
elrond-wasm/src/types/interaction/transfer_execute.rs

It has been made a change in Arwen such that when a smart contract A calls direct esdt execute with function call to smart contract B and that function returns sc_error, the execution will continue in A. So return values from send api functions will be needed to check if the function call returned with success or not. Return value of 0 indicates success and != 0 indicates failure. Tested on DEX smart contracts.

Added return value to send api functions

---

elrond-wasm/src/api/send_api.rs

Identified this as being a case where a lot of contracts might do the handle independently, each on their own.
Think it's best we do the handling in the framework.

added esdt transfer and send functions for any ESDT

---

contracts/examples/crowdfunding-erc20/src/lib.rs
contracts/examples/crypto-kitties/kitty-auction/src/lib.rs
contracts/examples/crypto-kitties/kitty-ownership/src/lib.rs
contracts/examples/erc1155-marketplace/src/lib.rs
contracts/examples/lottery-erc20/src/lib.rs
contracts/feature-tests/async/async-alice/src/lib.rs
contracts/feature-tests/async/forwarder/src/call_async.rs
contracts/feature-tests/async/forwarder/src/call_sync.rs
contracts/feature-tests/async/recursive-caller/src/lib.rs
contracts/feature-tests/execute-on-dest-esdt-issue-callback/parent/src/lib.rs
elrond-wasm-debug/tests/sample_adder.rs
elrond-wasm-derive/src/contract_impl.rs
elrond-wasm-derive/src/generate/auto_impl.rs
elrond-wasm-derive/src/generate/auto_impl_proxy.rs
elrond-wasm-derive/src/generate/mod.rs
elrond-wasm-derive/src/generate/proxy_gen.rs
elrond-wasm-derive/src/generate/snippets.rs
elrond-wasm-derive/src/generate/supertrait_gen.rs
elrond-wasm-derive/src/model/method.rs
elrond-wasm-derive/src/parse/attributes/attr_names.rs
elrond-wasm-derive/src/parse/attributes/endpoint_attr.rs
elrond-wasm-derive/src/parse/method_impl_parse.rs
elrond-wasm-derive/src/parse/mod.rs
elrond-wasm-derive/src/parse/split_path.rs
elrond-wasm-derive/src/parse/supertrait_parse.rs

Added `#[proxy]` getter syntax.
It has 2 roles:
- makes the syntax look cleaner
- automatically takes care of the `use module::ProxyTrait as _` imports
Note:
Avoid importing them from modules, the syntax will work but the import will not come automatically.

Call proxy redesign - `#[proxy]` getter

---

contracts/feature-tests/async/forwarder/src/nft.rs
contracts/feature-tests/local-esdt-and-nft/src/lib.rs
elrond-wasm-node/src/api/blockchain_api_node.rs
elrond-wasm/src/api/send_api.rs
elrond-wasm/src/types/general/esdt_token_data.rs

Hash is now 128 bytes length.
SCs will have to know the hash length to make use of this and take the appropriate slice.

make nft hash variable length

---

elrond-wasm/src/types/general/h256.rs

Optimize from_slice to use copy_from_slice instead of manually copying each element in a while loop.

from_slice optimization

---

contracts/examples/crowdfunding-esdt/src/lib.rs
contracts/examples/egld-esdt-swap/src/lib.rs
contracts/examples/esdt-nft-marketplace/src/lib.rs
contracts/examples/lottery-esdt/src/lib.rs
contracts/feature-tests/async/forwarder-raw/src/lib.rs
contracts/feature-tests/async/forwarder/src/call_sync.rs
contracts/feature-tests/async/forwarder/src/call_transf_exec.rs
contracts/feature-tests/async/forwarder/src/esdt.rs
contracts/feature-tests/async/forwarder/src/nft.rs
contracts/feature-tests/async/forwarder/src/roles.rs
contracts/feature-tests/async/vault/src/lib.rs
contracts/feature-tests/basic-features/src/blockchain_api_features.rs
contracts/feature-tests/esdt-contract-pair/first-contract/src/lib.rs
contracts/feature-tests/execute-on-dest-esdt-issue-callback/parent/src/lib.rs
contracts/feature-tests/local-esdt-and-nft/src/lib.rs
elrond-wasm-debug/src/api/blockchain_api_mock.rs
elrond-wasm-debug/src/api/send_api_mock.rs
elrond-wasm-node/src/api/blockchain_api_node.rs
elrond-wasm-node/src/api/send_api_node.rs
elrond-wasm/src/api/blockchain_api.rs
elrond-wasm/src/api/send_api.rs
elrond-wasm/src/api/uncallable/send_api_uncallable.rs
elrond-wasm/src/esdt/system_sc_proxy.rs
elrond-wasm/src/types/general/token_identifier.rs
elrond-wasm/src/types/interaction/contract_call.rs
elrond-wasm/src/types/interaction/send_esdt.rs
elrond-wasm/src/types/interaction/send_token.rs

Using built-in TokenIdentifier instead of &[u8] slice everywhere.
Removing some functions from send-api that just mask other functions.
Fixing contracts accordingly.

Framework functions cleanup

---

contracts/feature-tests/basic-features/mandos/sc_result.scen.json
contracts/feature-tests/basic-features/src/macros.rs
elrond-wasm/src/types/io/sc_result.rs

This pull request allows the use of `?` on `Result` types inside methods which return `SCResult`.
Some common cases where this would be needed are:
- when calling `Option::ok_or` - usage: `value.ok_or("error message")?;`
Note: there's an implicit conversion of the error message from `&str` to `SCResult`.
- when a function which returns a `Result<T, SCError>`

Add FromResidual for SCResult from Result

---

contracts/examples/esdt-nft-marketplace/mandos/auction_end_deadline.scen.json
contracts/examples/esdt-nft-marketplace/mandos/auction_end_max_bid.scen.json
contracts/examples/esdt-nft-marketplace/mandos/auction_sell_all_end_deadline.scen.json
contracts/examples/esdt-nft-marketplace/mandos/auction_sell_one_by_one_end_deadline.scen.json
contracts/examples/esdt-nft-marketplace/mandos/auction_sft_sell_all.scen.json
contracts/examples/esdt-nft-marketplace/mandos/auction_sft_sell_one_by_one.scen.json
contracts/examples/esdt-nft-marketplace/mandos/auction_token.scen.json
contracts/examples/esdt-nft-marketplace/mandos/auction_with_start_time.scen.json
contracts/examples/esdt-nft-marketplace/mandos/bid_first.scen.json
contracts/examples/esdt-nft-marketplace/mandos/bid_max.scen.json
contracts/examples/esdt-nft-marketplace/mandos/bid_second.scen.json
contracts/examples/esdt-nft-marketplace/mandos/bid_sft_sell_all_first.scen.json
contracts/examples/esdt-nft-marketplace/mandos/bid_sft_sell_all_second.scen.json
contracts/examples/esdt-nft-marketplace/mandos/bid_sft_sell_one_by_one_first.scen.json
contracts/examples/esdt-nft-marketplace/mandos/bid_sft_sell_one_by_one_second.scen.json
contracts/examples/esdt-nft-marketplace/mandos/buy_sft_after_end_auction.scen.json
contracts/examples/esdt-nft-marketplace/mandos/init.scen.json
contracts/examples/esdt-nft-marketplace/mandos/invalid_bids.scen.json
contracts/examples/esdt-nft-marketplace/mandos/specific_token_auctioned.scen.json
contracts/examples/esdt-nft-marketplace/mandos/view_functions.scen.json
contracts/examples/esdt-nft-marketplace/mandos/withdraw.scen.json
contracts/examples/esdt-nft-marketplace/mandos/withdraw_after_end_auction.scen.json
contracts/examples/esdt-nft-marketplace/src/auction.rs
contracts/examples/esdt-nft-marketplace/src/lib.rs
contracts/examples/esdt-nft-marketplace/src/storage.rs
contracts/examples/esdt-nft-marketplace/src/views.rs

Some refactoring: splitting into modules and moving some code from endpoints into private functions.
SFTs with custom quantity are now supported. They can also be sold one at a time through a single auction.

Nft marketplace sft support

---

contracts/examples/crowdfunding-erc20/src/crowdfunding_erc20.rs
contracts/examples/crowdfunding-esdt/src/crowdfunding_esdt.rs
contracts/examples/crypto-kitties/kitty-ownership/src/lib.rs
contracts/examples/egld-esdt-swap/src/swap.rs
contracts/examples/erc1155-marketplace/src/lib.rs
contracts/examples/esdt-nft-marketplace/src/marketplace_main.rs
contracts/examples/lottery-esdt/src/lottery.rs
contracts/examples/ping-pong-egld/src/ping_pong.rs
contracts/feature-tests/composability/forwarder-raw/src/forwarder_raw.rs
contracts/feature-tests/composability/forwarder/src/esdt.rs
contracts/feature-tests/composability/forwarder/src/nft.rs
contracts/feature-tests/composability/local-esdt-and-nft/src/lib.rs
contracts/feature-tests/composability/vault/src/vault.rs
contracts/modules/elrond-wasm-module-esdt/src/lib.rs
contracts/modules/elrond-wasm-module-governance/src/lib.rs
elrond-wasm/src/api/blockchain_api.rs
elrond-wasm/src/api/send_api.rs
elrond-wasm/src/types/interaction/send_esdt.rs
elrond-wasm/src/types/interaction/send_token.rs

- `self.send().direct()` now takes a nonce as argument. `direct_nft` removed.
- combined `esdt_local_mint` and `esdt_nft_add_quantity`
- combined `esdt_local_burn` and `esdt_nft_burn`

combine some send_api functions + update in contracts

---

.gitignore
tools/mandos-scripts/format.py

Added several python functions in order to allow easy generation of mandos code.
For the examples, see the python doctests.
Known limitations:
- top encoding / nested encoding isn't handled and as such the generated code may have to be manually modified
- the same goes for maps from which elements have been removed at some point, where indices are non-consecutive

Add mandos format script for storage collections

---

contracts/examples/multisig/src/multisig.rs
contracts/feature-tests/composability/execute-on-dest-esdt-issue-callback/parent/src/lib.rs
contracts/feature-tests/composability/forwarder/src/contract_deploy.rs
elrond-wasm-debug/src/api/send_api_mock.rs
elrond-wasm-node/src/api/send_api_node.rs
elrond-wasm/src/api/send_api.rs
elrond-wasm/src/api/uncallable/send_api_uncallable.rs

Changed the `deploy_contract` method to return an `Option<Address>` so that the user doesn't have to check if the address is 0 if the deployment fails.
The idiomatic way to check for a failed deployment is now:
```
let new_address = self
.send()
.deploy_contract(gas_left, &amount, &code, code_metadata, &arg_buffer)
.ok_or("Contract deployment failed")?;
```

Changed deploy_contract to return Option<Address>

---

.github/workflows/actions.yml
.github/workflows/release-upload.yml

Only starts when pressing the "Publish Release" button.
No more flooding git with tags that no-one asked for.
Seems to be working.

GitHub Action - Upload assets on release

---

contracts/examples/crypto-kitties/kitty-auction/src/auction.rs
contracts/feature-tests/basic-features/mandos/managed_vec_push.scen.json
contracts/feature-tests/basic-features/src/basic_features_main.rs
contracts/feature-tests/basic-features/src/managed_vec_features.rs
contracts/feature-tests/basic-features/tests/basic_features_mandos_go_test.rs
contracts/feature-tests/basic-features/tests/basic_features_mandos_rs_test.rs
elrond-wasm-debug/src/api/managed_types/big_int_util.rs
elrond-wasm-node/src/api/blockchain_api_node.rs
elrond-wasm-node/src/api/call_value_api_node.rs
elrond-wasm-node/src/api/send_api_node.rs
elrond-wasm/src/api/blockchain_api.rs
elrond-wasm/src/api/helpers/serializer.rs
elrond-wasm/src/io/arg_de_input.rs
elrond-wasm/src/io/finish.rs
elrond-wasm/src/io/signal_error.rs
elrond-wasm/src/log_util.rs
elrond-wasm/src/storage/storage_get.rs
elrond-wasm/src/storage/storage_key.rs
elrond-wasm/src/storage/storage_set.rs
elrond-wasm/src/types/general/esdt_token_data.rs
elrond-wasm/src/types/managed/big_int.rs
elrond-wasm/src/types/managed/big_uint.rs
elrond-wasm/src/types/managed/elliptic_curve.rs
elrond-wasm/src/types/managed/managed_buffer.rs
elrond-wasm/src/types/managed/managed_type_trait.rs
elrond-wasm/src/types/managed/managed_vec.rs
elrond-wasm/src/types/managed/managed_vec_item.rs
elrond-wasm/src/types/managed/managed_vec_iter.rs
elrond-wasm/src/types/managed/mod.rs
tools/test-gen/src/test_gen.rs

A structure based on a managed buffer, that can hold meaningful content.
Can be used to create "managed list of managed buffers" or of other managed types.
Highly extensible.
The idea is to use a managed buffer containing handles to other managed buffers to send log topics to Arwen, or to pass arguments. Also to retrieve results from execute_on_dest_context.

ManagedVec

---

contracts/feature-tests/basic-features/mandos/storage_mapper_token_attributes.scen.json
contracts/feature-tests/basic-features/src/storage_mapper_token_attributes.rs
elrond-wasm/src/storage/mappers/token_attributes_mapper.rs

This PR extends the functionality of token attributes mapper by adding the functions needed to query the nonce of an already created token by its attributes. It should be used as a cache as following: instead of creating the same token (meaning a token with the same attributes as a  previously created one), one can just query for existing nonce by attributes and use AddQuantity instead of Create, thus decreasing the number of nonces a token may have.

Extend Token Attr Mapper

---

elrond-wasm-derive/src/preprocessing/substitution_algorithm.rs

Add span information to the substitutions made. This means that error messages now show the exact line where the problem occurs. An example error is presented below, with before & after:
**Before:**
```
error[E0107]: this struct takes 2 generic arguments but 3 generic arguments were supplied
--> contracts/examples/egld-esdt-swap/src/swap.rs:11:1
|
11 | #[elrond_wasm::contract]
| ^^^^^^^^^^^^^^^^^^^^^^^^
| |
| expected 2 generic arguments
| help: remove this generic argument
|
note: struct defined here, with 2 generic parameters: `SA`, `T`
--> /home/claudiu/code/elrond-wasm-rs/elrond-wasm/src/storage/mappers/single_value_mapper.rs:12:12
|
12 | pub struct SingleValueMapper<SA, T>
|            ^^^^^^^^^^^^^^^^^ --  -
= note: this error originates in the attribute macro …
```

Add span information to error messages

---

contracts/feature-tests/basic-features/mandos/sc_result.scen.json
contracts/feature-tests/basic-features/src/macro_features.rs
elrond-wasm-derive/src/preprocessing/substitution_list.rs
elrond-wasm/src/types/io/sc_error.rs
elrond-wasm/src/types/io/sc_error_managed.rs
elrond-wasm/src/types/io/sc_error_static.rs
elrond-wasm/src/types/io/sc_result.rs

Add `unwrap_or_signal_error()` in order to signal errors and exit immediately, without returning a `SCResult`.
Makes use of the macro substitution to avoid specifying the api.
Usage:
`let unwrapped = result.unwrap_or_signal_error();`

add `unwrap_or_signal_error()` method for `SCResult`

---

contracts/examples/multisig/src/multisig.rs
contracts/examples/multisig/src/multisig_state.rs
contracts/examples/multisig/tests/multisig_mandos_go_test.rs

this led to a 1,5 kB decrease in the size of the contract

change signers storage type to UnorderedSetMapper

---

elrond-wasm-debug/tests/managed_vec_test.rs
elrond-wasm-derive/src/preprocessing/substitution_list.rs
elrond-wasm/src/types/managed/managed_vec_iter.rs

- add `size_hint` implementation, which is needed for `ExactSizeIterator`
- add `Clone` for `ManagedVecIterator`
- update macro replacement rules for `ManagedVecIterator` to allow skipping `Self::Api` when passing an iterator as a function argument
- add tests

Implement `ExactSizeIterator` for `ManagedVecIterator`

---

tools/erdpy-snippet-generator/src/cmd_builder.rs
tools/erdpy-snippet-generator/src/erdpy_snippet_generator.rs

Add option in erdpy snippet generator to generate tx data in the `endpointName@arg1hex@arg2hex...` format as well

generate tx data

---

elrond-wasm-debug/src/api/managed_types/static_buffer_api_mock.rs
elrond-wasm-node/src/api/managed_types/static_buffer_api_node.rs
elrond-wasm/src/api/managed_types/managed_type_api.rs
elrond-wasm/src/api/managed_types/mod.rs
elrond-wasm/src/api/managed_types/static_var_api.rs
elrond-wasm/src/api/uncallable/static_buffer_api_uncallable.rs
elrond-wasm/src/types/static_buffer/static_buffer_ref.rs

The reason is: there will be more static variables there, beside the static buffer.

API refactor - renamed StaticBufferApi to StaticVarApi

---

.github/workflows/actions.yml
contracts/examples/crowdfunding-esdt/src/crowdfunding_esdt.rs
contracts/examples/crowdfunding-esdt/tests/crowdfunding_esdt_rust_test.rs
contracts/examples/crypto-bubbles/src/crypto_bubbles.rs
contracts/examples/digital-cash/tests/digital_cash_mandos_go_test.rs
contracts/examples/digital-cash/tests/digital_cash_mandos_rs_test.rs
contracts/examples/egld-esdt-swap/src/swap.rs
contracts/examples/nft-storage-prepay/src/nft_storage_prepay.rs
contracts/feature-tests/basic-features/src/macro_features.rs
contracts/feature-tests/erc-style-contracts/erc20/src/erc20.rs
contracts/feature-tests/formatted-message-features/src/formatted_message_features.rs
contracts/feature-tests/rust-testing-framework-tester/src/lib.rs
contracts/feature-tests/rust-testing-framework-tester/tests/rust_testing_framework-test.rs
contracts/feature-tests/use-module/use_module_expected_main.abi.json
elrond-wasm-debug/src/mandos_step/transfer.rs
elrond-wasm-debug/src/testing_framework/contract_obj_wrapper.rs
elrond-wasm-debug/src/tx_execution/exec_contract_endpoint.rs
elrond-wasm-debug/src/tx_mock/tx_result.rs
elrond-wasm-derive/src/format/format_args_macro.rs
elrond-wasm-modules/src/dns.rs
elrond-wasm-modules/src/esdt.rs
elrond-wasm-modules/src/governance/governance_configurable.rs
elrond-wasm/src/contract_base/wrappers/error_helper.rs
elrond-wasm/src/macros.rs

- `require!` calls signal_error immediately instead of return a sc error result
- the testing framework now handles panics

`require!` macro redesign + Rust testing framework panic handling

---

elrond-wasm-node/src/api/send_api_node_impl_legacy.rs
elrond-wasm-node/src/api/send_api_node_impl_managed.rs
elrond-wasm/src/types/general/code_metadata.rs

Using `bitfield!` macro makes everything more compact.
Some small additional benefits might come from using `u16` instead of `[u8; 2]` everywhere.

CodeMetadata refactor

---

contracts/feature-tests/abi-tester/abi_tester_expected_main.abi.json
contracts/feature-tests/abi-tester/abi_tester_expected_view.abi.json
contracts/feature-tests/abi-tester/src/abi_test_type.rs
contracts/feature-tests/abi-tester/src/abi_tester.rs
contracts/feature-tests/abi-tester/src/only_nested.rs
elrond-wasm/src/abi/type_abi.rs
elrond-wasm/src/types/managed/managed_vec.rs

ABI was not being provided for contents of Vec, ManagedBec, boxed slice and slice.

abi - nested type bugfix

---

contracts/examples/token-release/src/token_release.rs
contracts/feature-tests/basic-features/src/storage_mapper_single.rs
elrond-wasm-derive/src/generate/method_gen.rs
elrond-wasm-derive/src/preprocessing/substitution_algorithm.rs
elrond-wasm-derive/src/preprocessing/substitution_list.rs

This should fix the broken error messages.
The substitution algorithm can be further improved a little bit, but I think the current code gets all errors right.

Preprocessor span fix

---

contracts/feature-tests/basic-features/src/types/codec_err_test_type.rs
elrond-codec/src/codec_err.rs
elrond-wasm-debug/src/managed_test_util.rs
elrond-wasm/src/types/general/h256.rs
elrond-wasm/src/types/io/sc_result.rs
elrond-wasm/src/types/managed/big_int.rs
elrond-wasm/src/types/managed/big_uint.rs
elrond-wasm/src/types/managed/managed_buffer.rs
elrond-wasm/src/types/managed/managed_byte_array.rs
elrond-wasm/src/types/managed/managed_multi_result_vec_counted.rs

Despite much refactoring, somehow several managed types still had their non-specialized decodes left not unimplemented.

Non-specialized decode for managed types

---

contracts/feature-tests/use-module/use_module_expected_main.abi.json
contracts/feature-tests/use-module/use_module_expected_view.abi.json
contracts/feature-tests/use-module/wasm/src/lib.rs
elrond-wasm-modules/src/esdt.rs

- use the new register and set all roles function
- add create NFT function
Note that this module is mostly going to be used in contracts that use the NFTs as a means of information, so we have no use for all the NFTCreate arguments.

ESDT module update

---

.github/workflows/actions.yml
contracts/examples/ping-pong-egld/mandos/ping-pong-call-pong-all-interrupted-1.scen.json
contracts/examples/ping-pong-egld/mandos/ping-pong-call-pong-all-interrupted-2.scen.json

- Enable `wasm-opt` optimizations by first installing the dependencies through erdpy
- Update the `pongAll` interrupt tests, which now require less gas for a single pong

Add `wasm-opt` to GitHub Actions

---

contracts/feature-tests/basic-features/mandos/storage_mapper_map.scen.json
contracts/feature-tests/basic-features/src/storage_mapper_map.rs
elrond-wasm/src/storage/mappers/map_mapper.rs

Add `#[view]` capabilities for `MapMapper<K, V>` which outputs it as a `MultiResultVec<MultiValue<K, V>>`.

Add view for MapMapper

---

elrond-wasm/src/contract_base/wrappers/crypto_wrapper.rs

- keccak hashing function was using the wrong constant for the result len (even if the value itself is the same)

fix wrong const

---

contracts/feature-tests/formatted-message-features/mandos/managed_error_message.scen.json
contracts/feature-tests/formatted-message-features/mandos/sc_format.scen.json
contracts/feature-tests/formatted-message-features/src/formatted_message_features.rs
contracts/feature-tests/formatted-message-features/tests/msg_mandos_go_test.rs
contracts/feature-tests/formatted-message-features/tests/msg_mandos_rs_test.rs
contracts/feature-tests/formatted-message-features/wasm/src/lib.rs
elrond-wasm/src/macros.rs

- add `sc_format!` macro which formats the messages into a `ManagedBuffer`
- tested the functionality with mandos-rs and mandos-go
- add an unrelated missing test for `decode_error_message`

Add `sc_format!` macro

---

elrond-wasm-debug/src/mandos_rs_runner.rs
elrond-wasm-debug/src/mandos_step/sc_call.rs
elrond-wasm-debug/src/mandos_step/sc_deploy.rs
elrond-wasm-debug/src/mandos_step/sc_query.rs
elrond-wasm-debug/src/mandos_step/set_state.rs
mandos/src/model/step.rs

Simple first step: changed the mandos `Step` enum to a more canonical form.

mandos step refactoring #1

---

.github/workflows/actions.yml

Use [`contracts.yml`](https://github.com/ElrondNetwork/elrond-actions/blob/v1/.github/workflows/contracts.yml) with the same configurations as before (rust nightly version, vmtools version, ignore eei checks flag).
Side notes:
- did not remove `.github/workflow/env` since it's still used by `.github/workflows/release-upload.yml`
- `./build-wasm.sh` is not used for github actions anymore since `erdpy contract build -r` is used now

Use elrond-actions contracts.yml v1

---

elrond-wasm-debug/src/testing_framework/helper_macros.rs
elrond-wasm-debug/tests/managed_token_identifier_test.rs

- account for the "EGLD" string

better token id macro

---

elrond-wasm/src/storage/mappers/single_value_mapper.rs

- consistent implementation for `SingleValueMapper` methods `set` and `set_if_empty`.

set if empty borrow trait

---

contracts/feature-tests/use-module/src/use_module.rs
contracts/feature-tests/use-module/tests/staking_module_test.rs
contracts/feature-tests/use-module/use_module_expected_main.abi.json
contracts/feature-tests/use-module/wasm/src/lib.rs
elrond-wasm-modules/src/lib.rs
elrond-wasm-modules/src/staking.rs

A staking module that can be integrated into other smart contracts. Provided features:
- basic staking/unstaking
- mechanism to slash a member's stake if they're voted to be slashed by a certain number of other members
- adding/removing board members
The contract integrating this can decide if any view functions are needed and what it decides to do with the slashed amounts.

staking module

---

elrond-wasm/src/storage/storage_key.rs
elrond-wasm/src/types/interaction/arg_buffer_managed.rs
elrond-wasm/src/types/managed/basic/big_int.rs
elrond-wasm/src/types/managed/basic/big_uint.rs
elrond-wasm/src/types/managed/basic/elliptic_curve.rs
elrond-wasm/src/types/managed/basic/managed_buffer.rs
elrond-wasm/src/types/managed/managed_type_trait.rs
elrond-wasm/src/types/managed/wrapped/managed_address.rs
elrond-wasm/src/types/managed/wrapped/managed_byte_array.rs
elrond-wasm/src/types/managed/wrapped/managed_vec.rs
elrond-wasm/src/types/managed/wrapped/token_identifier.rs

`#[doc(hidden)]` placed on implementations doesn't really make sense and is now a Rust warning

warning fix

---

elrond-wasm/src/contract_base/wrappers/send_wrapper.rs

- convenience method for sending `EsdtTokenPayment` directly instead of manually splitting the fields and using `self.send().direct()`

send single payment

---

elrond-wasm-debug/tests/test_hash_unordered_set_mapper.rs
elrond-wasm/src/storage/mappers/unordered_set_mapper.rs

feature: `get_by_index` gets an item at index from storage
Index must be valid (1 <= index <= count).

get by index + small test

---

elrond-wasm-debug/src/mandos_system/executor/mod.rs
elrond-wasm-debug/src/mandos_system/executor/sc_call.rs
elrond-wasm-debug/src/mandos_system/executor/sc_deploy.rs
elrond-wasm-debug/src/mandos_system/executor/sc_query.rs
elrond-wasm-debug/src/mandos_system/model/mod.rs
elrond-wasm-debug/src/mandos_system/model/step/mod.rs
elrond-wasm-debug/src/mandos_system/model/step/step_enum.rs
elrond-wasm-debug/src/mandos_system/model/step/step_set_from_proxy.rs
elrond-wasm-debug/src/mandos_system/model/step/step_sugar.rs

Because we moved the code around, this trick is no longer needed.

simplified mandos proxy setters

---

elrond-wasm/src/types/interaction/contract_call.rs

- decode to any type provided by the caller instead of restricting by CodecFrom. The previous implementation makes it almost impossible to integrate existing mainnet contracts, as they often have an older elrond-wasm version, meaning some types have different implementations, unwanted results are being propagated, etc.
- also added result for execute_on_same_context, which was previously ignored.

decode results to any type for sync calls

---

contracts/examples/token-release/src/token_release.rs

It seems that the `require_setup_period_live();` method should be called at `end_setup_period`. Otherwise, this method could be called by the owner multiple times and more tokens will be minted.

added missing require

---

contracts/core/price-aggregator/README.md
contracts/core/price-aggregator/src/lib.rs
contracts/core/price-aggregator/src/price_aggregator_data.rs
contracts/core/price-aggregator/tests/price_agg_setup/mod.rs
contracts/core/price-aggregator/tests/price_agg_tests.rs
contracts/core/price-aggregator/wasm/src/lib.rs

- changed the `decimals` configuration from global to one-per-pair
- added endpoints for interacting with the `decimals` configuration: `setPairDecimals`, `getPairDecimals`
- breaking change: the `submit` and `submitBatch` endpoints must now provide the `decimals` as well, to ensure that a submission is not interpreted with the wrong number of decimals by mistake
- updated the existing tests
- updated the documentation

Price aggregator decimals change

---

elrond-wasm-debug/tests/managed_vec_test.rs
elrond-wasm/src/types/managed/wrapped/managed_vec.rs

With this PR, devs can use the more ergonomic collect fn instead of manually doing a for_each or for loop over the filtered/mapped iterator
Before:
```rust
let mut collected_vec: ManagedVec<i32> = ManagedVec::new();
managed_vec.iter().filter(|x| x <= &5).for_each(|el| collected_vec.push(el));
```
After:
```rust
let collected_vec = managed_vec.iter().filter(|x| x <= &5).collect::<ManagedVec<i32>>();
```

implement FromIterator trait for ManagedVec

---

elrond-wasm-debug/tests/managed_vec_test.rs
elrond-wasm/src/types/managed/wrapped/managed_vec.rs

By implementing the Extend trait for ManagedVec, developers can use partition when iterating over ManagedVecs
Example:
```rust
let (collected_vec1, collected_vec2) = managed_vec
.iter()
.partition::<ManagedVec<DebugApi, i32>, _>(|x| x <= &5);
```
PS: this time with a verified commit :)

implement Extend trait for ManagedVec

---

contracts/examples/multisig/mandos/call_other_shard-1.scen.json
contracts/examples/multisig/mandos/changeBoard.scen.json
contracts/examples/multisig/mandos/steps/rem_unknown.steps.json
contracts/examples/multisig/src/multisig_perform.rs
contracts/examples/multisig/src/multisig_propose.rs
contracts/examples/multisig/tests/multisig_rust_test.rs
contracts/examples/multisig/wasm/Cargo.lock
elrond-codec/src/multi_types/multi_value_optional.rs
elrond-wasm/src/storage/mappers/user_mapper.rs

Short description of audit findings:
1. variable does not need to be mutable
Severity: Informative | Category: Code Quality
Description: user_count does not need to be mutable in UserMapper.get_or_create_user.
Recommendation: Change the code so that user_count is not mutable.
2. Issue: variable does not need to be mutable
Severity: Informative | Category: Code Quality
Description: user_id probably does not need to be mutable in UserMapper.get_or_create_users
Recommendation: Change the code so that user_id is not mutable.
3. Issue: Users added to storage when deleting
Severity: Low | Difficulty: High | Category: Improvement
Description: The multisig code identifies that a user is not known to the contract by checking whether his role is None. Besides that, usually the multisig code gets a …

Multisig fixes after audit

---

elrond-codec/src/impl_for_types/impl_bool.rs
elrond-codec/src/impl_for_types/impl_num_signed.rs
elrond-codec/src/impl_for_types/impl_num_unsigned.rs
elrond-codec/src/impl_for_types/impl_unit.rs
elrond-codec/src/impl_for_types/local_macro.rs
elrond-codec/src/single/mod.rs
elrond-codec/src/single/nested_en.rs
elrond-codec/src/single/top_en.rs
elrond-codec/tests/derive_hygiene.rs
elrond-codec/tests/explicit_impl_enum.rs

They were introduced long ago for potential performance improvements and code reuse, but they are completely unnecessary now and can lead to confusion.

removed TopEncodeNoErr and NestedEncodeNoErr

---

elrond-codec/src/impl_for_types/impl_array.rs
elrond-codec/src/impl_for_types/impl_bool.rs
elrond-codec/src/impl_for_types/impl_num_signed.rs
elrond-codec/src/impl_for_types/impl_num_unsigned.rs
elrond-codec/src/impl_for_types/impl_slice.rs
elrond-codec/src/impl_for_types/impl_unit.rs
elrond-codec/src/impl_for_types/impl_vec.rs
elrond-codec/src/impl_for_types/local_macro.rs
elrond-codec/src/lib.rs
elrond-codec/src/single/nested_de.rs
elrond-codec/src/single/nested_en.rs
elrond-codec/src/single/top_de.rs
elrond-codec/src/single/top_en.rs
elrond-wasm/src/formatter/formatter_impl_num.rs

There are better ways to do monomorphization. Also showcased here.
In short:
```
T::if_u8(
input,
|input| {
...
},
|input| {
...
},
)
```
is more specific and cleaner than
```
if let TypeInfo::U8 = T::TYPE_INFO {
...
} else {
...
}
```
... even if they amount to pretty much the same result in the end.
With that out of the way, `TypeInfo` is a relic from the SCALE codec we initially took some inspiration from, and is ready to go!

Remove TypeInfo from codec

---

.github/workflows/lldb-formatter-tests.yml
elrond-wasm-debug/src/api/mod.rs
tools/rust-debugger/format-tests/Cargo.toml
tools/rust-debugger/format-tests/src/check_debugger_values.py
tools/rust-debugger/format-tests/src/format_tests.rs
tools/rust-debugger/format-tests/src/mypy.ini
tools/rust-debugger/format-tests/tests/run_format_tests.rs
tools/rust-debugger/pretty-printers/elrond_wasm_lldb_pretty_printers.py
tools/rust-debugger/pretty-printers/mypy.ini

Added `elrond_wasm_lldb_pretty_printers.py` - a script which contains pretty printers for most managed types, in order to display them properly when running the rust debugger on any contract test. This script is automatically loaded by LLDB (the debugger used by rust), provided that it has been installed. The installation of the script is handled by the Elrond VS code extension in PR https://github.com/ElrondNetwork/elrond-ide-vscode/pull/55.
Added unit tests in the `tools/rust-debugger/format-tests` folder, as well as a github action (`.github/workflows/lldb-formatter-tests.yml`) which runs them. The tests are structured as follows:
- In `format-tests/src/format_tests.rs` we set up some variables (managed types, collections etc.) that we want to check, together with their expected …

Add lldb pretty printers

---

Cargo.toml
coverage.sh
elrond-wasm-node/src/api/managed_types/managed_buffer_api_node.rs

After playing around, accomplished the following:
- Included `elrond-wasm-node` in workspace
- Coverage script fix - this was the reason `elrond-wasm-node` was out. This problem seems fixed now.
- Perk: we now have build checks, clippy and fmt for `elrond-wasm-node`.

`elrond-wasm-node` back into the workspace

---

contracts/examples/multisig/mandos/sendEsdt.scen.json
contracts/examples/multisig/src/multisig_perform.rs
contracts/examples/multisig/wasm-multisig-full/src/lib.rs
contracts/examples/multisig/wasm/src/lib.rs
contracts/feature-tests/composability/promises-features/src/call_promise_direct.rs
elrond-wasm-debug/src/meta/output_contract/output_contract_model.rs
elrond-wasm-debug/src/world_mock/blockchain_mock_init.rs
elrond-wasm-debug/src/world_mock/contract_container.rs

A simple callback to log async results. Useful for interacting with the contract.
Also found a bug in the multi-contract debugger (the callback was not properly functional).

multisig async call callback

---

contracts/examples/seed-nft-minter/src/distribution_module.rs
contracts/feature-tests/composability/forwarder-raw/src/forwarder_raw.rs
contracts/feature-tests/composability/forwarder/src/call_async.rs
contracts/feature-tests/composability/forwarder/src/call_queue.rs
contracts/feature-tests/composability/forwarder/src/call_sync.rs
contracts/feature-tests/composability/forwarder/src/call_transf_exec.rs
contracts/feature-tests/composability/promises-features/src/call_promise_direct.rs
contracts/feature-tests/composability/promises-features/src/call_promises.rs
contracts/feature-tests/composability/recursive-caller/src/recursive_caller.rs
contracts/feature-tests/use-module/src/contract_base_full_path_mod.rs
contracts/feature-tests/use-module/src/contract_base_mod.rs
contracts/feature-tests/use-module/src/use_module.rs
elrond-wasm-derive/src/generate/proxy_gen.rs
elrond-wasm-derive/src/parse/contract_trait_parse.rs
elrond-wasm-derive/src/parse/supertrait_parse.rs
elrond-wasm/src/types/interaction/contract_call.rs
elrond-wasm/src/types/interaction/contract_call_deprecated.rs
elrond-wasm/src/types/interaction/mod.rs
elrond-wasm/src/types/managed/wrapped/egld_or_esdt_token_payment.rs
elrond-wasm/src/types/managed/wrapped/esdt_token_payment.rs

ContractCall accepts payment info both as tuple and as payment object.
Deprecated the old methods.

ContractCall - allow full ESDT payment obj as arg

---

framework/base/src/api/builtin_function_names.rs
framework/debug/src/tx_execution/builtin_function_mocks/general/migrate_username_mock.rs
framework/debug/src/tx_execution/builtin_function_mocks/general/mod.rs

- add mock for the `migrateUserName` builtin function, which migrates a username from `.elrond` to a `.x` suffix

Add migrateUserName builtin function mock

---

framework/meta/src/cli_args/cli_args_standalone.rs
framework/meta/src/folder_structure/mod.rs
framework/meta/src/folder_structure/pretty_print.rs
framework/meta/src/folder_structure/relevant_directory.rs
framework/meta/src/lib.rs
framework/meta/src/meta_all.rs
framework/meta/src/meta_cli.rs
framework/meta/src/meta_info.rs
framework/meta/src/sc_upgrade/mod.rs
framework/meta/src/sc_upgrade/upgrade_0_31.rs
framework/meta/src/sc_upgrade/upgrade_0_32.rs
framework/meta/src/sc_upgrade/upgrade_0_39.rs
framework/meta/src/sc_upgrade/upgrade_common.rs
framework/meta/src/sc_upgrade/upgrade_print.rs
framework/meta/src/sc_upgrade/upgrade_selector.rs
framework/meta/src/sc_upgrade/upgrade_versions.rs

- New command: `sc-meta info` shows a pretty tree with all contracts and contract libraries in a folder
- Upgrade supports releases as early as `0.28.0`.

sc-meta improvements

---

framework/base/src/api/managed_types/managed_type_api_impl.rs
framework/base/src/api/managed_types/token_identifier_util.rs
framework/base/src/err_msg.rs
framework/base/src/types/managed/wrapped/token_identifier.rs
framework/scenario/tests/token_identifier_test.rs

The `ticker` method returns the ticker of the token identifier.

Add ticker method to TokenIdentifier

---

framework/base/src/types/managed/basic/managed_buffer.rs

The `ManagedArgBuffer` has a `.concat` method:
https://github.com/multiversx/mx-sdk-rs/blob/master/framework/base/src/types/interaction/arg_buffer_managed.rs#L149
This PR adds this `.concat` method to ManagedBuffer.

Add `.concat()` method to ManagedBuffer

---

framework/base/src/abi/contract_abi.rs
framework/meta/src/meta_validate_abi.rs

Prevents developers from accidentally mixing var-args and regular ones the wrong way.
We can also reduce it to just a warning in the future, if somebody needs it. However, I don't currently see why that might be.

validating var-args based on ABI when building

---

framework/base/src/api/call_value_api.rs
framework/base/src/api/uncallable/call_value_api_uncallable.rs
framework/base/src/contract_base/wrappers/call_value_wrapper.rs
framework/wasm-adapter/src/api/call_value_api_node.rs
vm/src/api/call_value_api_mock.rs
vm/src/api/managed_types/big_int_api_mock.rs

Little PR brother of https://github.com/multiversx/mx-sdk-rs/pull/1045
Since it is cleanup season, decided to also get rid of the old single ESDT call value API methods. They don't work well in the context of multi-transfer, so they have been long out of use.

removed api single esdt methods

---

contracts/feature-tests/composability/vault/src/vault.rs

Vault, as a child SC will respond with transfer_execute instead of async_call to parent.

vault: transfer_execute instead of async call

---

framework/base/src/types/managed/wrapped/managed_vec_item.rs
vm/tests/derive_managed_vec_item_struct_2_test.rs

Popped up on telegram, someone needed an array in a `ManagedVecItem`.
The implementation is pretty straightforward, we just concatenate the payloads.
Also removed `MAX_PAYLOAD_SIZE`, the Rust compiler finally got smart enough to allow to do associated const generic arithmetic in array declarations.

ManagedVecItem implementation for arrays

---

contracts/feature-tests/composability/forwarder-raw/src/forwarder_raw_alt_init.rs
contracts/feature-tests/composability/forwarder-raw/wasm-forwarder-raw-init-async-call/src/lib.rs

Some leftover code. We don't have a test for it yet, but didn't want it to get lost either.

forwarder-raw upgrade_async_call endpoint

---

vm/Cargo.toml
vm/src/lib.rs
vm/src/mem_conv.rs
vm/src/vm_hooks/vh_dispatcher.rs

Finally the VM has a proper reference to the executor interface.

using multiversx-chain-vm-executor v0.1.0

---

contracts/feature-tests/use-module/use_module_expected_main.abi.json
contracts/feature-tests/use-module/use_module_expected_view.abi.json
framework/base/src/abi/type_abi.rs
framework/base/src/abi/type_description.rs
framework/base/src/types/io/operation_completion_status.rs
framework/meta/src/abi_json/type_abi_json.rs

Sample output:
```
"OperationCompletionStatus": {
"type": "explicit-enum",
"variants": [
{
"docs": [
"indicates that operation was completed"
],
"name": "completed"
},
{
"docs": [
"indicates that operation was interrupted prematurely, due to low gas"
],
"name": "interrupted"
}
]
},
```

explicit enum ABI

---

framework/base/src/api/send_api.rs
framework/base/src/api/uncallable/send_api_uncallable.rs
framework/base/src/contract_base/wrappers/send_raw_wrapper.rs
framework/wasm-adapter/src/api/send_api_node.rs
vm/src/api/blockchain_api_mock.rs
vm/src/api/call_value_api_mock.rs
vm/src/api/send_api_mock.rs
vm/src/tx_mock/tx_input.rs
vm/src/tx_mock/tx_input_function.rs
vm/src/tx_mock/tx_managed_types/tx_big_int.rs
vm/src/tx_mock/tx_managed_types/tx_managed_buffer.rs
vm/src/vm_hooks/vh_handler/vh_blockchain.rs
vm/src/vm_hooks/vh_handler/vh_call_value.rs
vm/src/vm_hooks/vh_handler/vh_log.rs

SendApi was the last unreformed API. It was still using high-level objects.
This long technical debt is finally fixed. It is now a very thin layer over the EI.

send api using only handles

---

contracts/feature-tests/rust-testing-framework-tester/tests/rust_mandos_v1_test.rs
framework/scenario/src/api/core_api_vh/blockchain_api_vh.rs
framework/scenario/src/api/core_api_vh/call_value_api_vh.rs
framework/scenario/src/api/core_api_vh/crypto_api_vh.rs
framework/scenario/src/api/core_api_vh/endpoint_arg_api_vh.rs
framework/scenario/src/api/core_api_vh/endpoint_finish_api_vh.rs
framework/scenario/src/api/core_api_vh/error_api_vh.rs
framework/scenario/src/api/core_api_vh/log_api_vh.rs
framework/scenario/src/api/core_api_vh/storage_api_vh.rs
framework/scenario/src/api/impl_vh/debug_api.rs
framework/scenario/src/api/impl_vh/debug_handle_vh.rs
framework/scenario/src/api/impl_vh/vm_hooks_api.rs
framework/scenario/src/api/impl_vh/vm_hooks_backend.rs
framework/scenario/src/api/managed_type_api_vh.rs
framework/scenario/src/api/managed_type_api_vh/big_float_api_vh.rs
framework/scenario/src/api/managed_type_api_vh/big_int_api_vh.rs
framework/scenario/src/api/managed_type_api_vh/managed_buffer_api_vh.rs
framework/scenario/src/api/managed_type_api_vh/managed_map_api_vh.rs
framework/scenario/src/whitebox/contract_obj_wrapper.rs
vm/src/api/managed_types/managed_buffer_api_mock.rs
vm/src/api/managed_types/managed_map_api_mock.rs
vm/src/api/managed_types/managed_type_api_mock.rs
vm/src/tx_mock/tx_context_ref.rs

Managed type APIs work on the context of the respective handles.
Unlike with the old API, all handles always need to be in the same context.
General APIs require that the handles are live, i.e. they refer to the current active context.

DebuggerApi - handle safety & context

---

framework/meta/src/cli_args/cli_args_build.rs
framework/meta/src/cli_args/cli_args_standalone.rs
framework/meta/src/cmd/contract/output_contract/oc_config.rs
framework/meta/src/cmd/contract/output_contract/wasm_build.rs
framework/meta/src/cmd/standalone/all.rs
framework/meta/src/print_util.rs

Requested by the community.
This feature allows us to explicitly set the target dir for both meta and wasm crates, whereas in the past it was just for the wasm crate.

sc-meta explicit CLI --target-dir-wasm and --target-dir-meta

---

Cargo.lock
framework/meta/Cargo.toml
framework/meta/src/cmd/contract/output_contract/wasm_build.rs
framework/meta/src/tools.rs
framework/meta/src/tools/post_build.rs
framework/meta/src/tools/wasm_imports.rs

This simplifies our dependencies, we no longer need the external tool `wasm-objdump` installed to run builds.

meta - replace wasm-objdump with internal impl

---

.gitignore
Cargo.lock
framework/meta/Cargo.toml
framework/meta/src/cmd/contract/meta_config.rs
framework/meta/src/cmd/contract/output_contract/wasm_build.rs
framework/meta/src/print_util.rs
framework/meta/src/tools.rs
framework/meta/src/tools/post_build.rs
framework/meta/src/tools/twiggy.rs
framework/meta/src/tools/wasm_opt.rs
framework/meta/src/tools/wasm_to_wat.rs

The library is called `wasmprinter`.
It aligns the wat code a little better than wasm2wat, I think:

Replace wasm2wat with internal implementation

---

framework/base/src/contract_base/wrappers/send_wrapper.rs
framework/base/src/esdt/system_sc_proxy.rs
framework/base/src/types/interaction/contract_call_trait.rs

contract call argument method

---

contracts/benchmarks/str-repeat/sc-config.toml
contracts/examples/multisig/sc-config.toml
contracts/feature-tests/abi-tester/sc-config.toml
contracts/feature-tests/basic-features/sc-config.toml
contracts/feature-tests/composability/forwarder-queue/sc-config.toml
contracts/feature-tests/composability/forwarder-raw/sc-config.toml
contracts/feature-tests/composability/proxy-test-first/sc-config.toml
contracts/feature-tests/erc-style-contracts/lottery-erc20/sc-config.toml
contracts/feature-tests/multi-contract-features/multicontract.toml
contracts/feature-tests/panic-message-features/sc-config.toml
contracts/feature-tests/rust-testing-framework-tester/sc-config.toml
contracts/feature-tests/use-module/sc-config.toml
framework/meta/src/cmd/contract/output_contract/oc_builder.rs
framework/meta/src/cmd/contract/output_contract/oc_config.rs
framework/meta/src/cmd/contract/output_contract/oc_settings.rs
framework/meta/src/cmd/contract/output_contract/oc_settings/oc_allocator.rs
framework/meta/src/ei/ei_version.rs
framework/meta/tests/multi_contract_test.rs

- `add-unlabelled` default `true`

Sc config update #2

---

contracts/examples/multisig/interact/src/multisig_interact_nfts.rs
contracts/examples/multisig/interact/src/multisig_interact_wegld.rs
contracts/examples/multisig/src/multisig_propose.rs
contracts/examples/multisig/tests/multisig_blackbox_test.rs
contracts/examples/multisig/tests/multisig_whitebox_test.rs
framework/base/src/types/interaction/async_call.rs
framework/base/src/types/interaction/async_call_promises.rs
framework/base/src/types/interaction/contract_call_convert.rs
framework/base/src/types/interaction/contract_call_exec.rs
framework/base/src/types/interaction/contract_call_no_payment.rs
framework/base/src/types/interaction/contract_call_trait.rs
framework/base/src/types/interaction/function_call.rs
framework/base/src/types/interaction/managed_arg_buffer.rs
framework/base/src/types/interaction/mod.rs
framework/base/src/types/managed/wrapped/esdt_token_data.rs
framework/derive/src/preprocessing/substitution_list.rs
framework/scenario/src/scenario/model/step/sc_call_step.rs
framework/scenario/tests/contract_call_test.rs
framework/snippets/src/interactor_sc_call.rs

Refactoring PR.
`FunctionCall` created to be used inside the framework, but also in contracts like the multisig. It can be encoded as a multi-value argument.
Also refactored some of the code formatting ESDT transfer calls.
Changes are also going to be used in the new unified syntax, but are useful enough on their own to deserve their own PR.

FunctionCall object

---

contracts/feature-tests/composability/promises-features/src/call_sync_bt.rs
contracts/feature-tests/composability/tests/promises_feature_blackbox_test.rs
vm/src/tx_mock/tx_back_transfers.rs
vm/src/vm_hooks/vh_impl/vh_debug_api.rs

Back transfers are not cleared after a call; therefore in a multi call transaction, back transfers are merged and multiple values are returned.

Fix/back transfers multi call payment 

---

.github/workflows/actions.yml
.github/workflows/lldb-formatter-tests.yml
.github/workflows/release-upload.yml
.github/workflows/template-test-current.yml
.github/workflows/template-test-released.yml

- Reference newer CI version: https://github.com/multiversx/mx-sc-actions/releases/tag/v2.3.5
- Allow some workflows to be ran on demand

Reference newer CI version. Allow some workflows to be ran on demand

---

contracts/feature-tests/composability/Cargo.toml
contracts/feature-tests/composability/forwarder-queue/Cargo.toml
contracts/feature-tests/composability/forwarder-queue/sc-config.toml
contracts/feature-tests/composability/forwarder-queue/src/forwarder_queue.rs
contracts/feature-tests/composability/forwarder-queue/wasm-forwarder-queue-promises/Cargo.toml
contracts/feature-tests/composability/promises-features/Cargo.toml
contracts/feature-tests/composability/vault/Cargo.toml
contracts/feature-tests/managed-map-features/Cargo.toml
contracts/feature-tests/multi-contract-features/multicontract.toml
framework/base/Cargo.toml
framework/base/src/contract_base/wrappers/blockchain_wrapper.rs
framework/base/src/types/interaction/contract_call_exec.rs
framework/base/src/types/interaction/contract_call_trait.rs
framework/base/src/types/managed/basic/mod.rs
framework/meta/Cargo.toml
framework/meta/src/cmd/contract/sc_config/multi_contract_serde.rs
framework/meta/src/cmd/contract/sc_config/oc_settings/oc_parse_stack_size.rs
framework/meta/src/ei/ei_version.rs

Also changed the default EI version from 1.2 to 1.3.
Also made the parsing of `sc-config.toml` strict (unrecognized fields no longer allowed)

Removed features: promises, managed-map, back-transfers

---

framework/scenario/src/scenario/model/transaction/tx_response.rs

The TxResponse's `process_new_issued_token_identifier` function is badly implemented. It tries to decode issued tokens on transaction which not issue any token. For example any setSpecialRoles result will trigger a token parsing, leading to a panic.
Moreover, the function is unable to decode issued fungible tokens since it relies on a result starting with `@ok@`, but in the case of a fungible token it is `ESDTTransfer@` which is returned.
I changed the function's logic to fix it.
No tests were written for this function so I added the following ones, by mocking the transaction data:
- a test ensuring the parsing works for a new issued fungible
- a test ensuring the parsing works for a new issued semi fungible
- a test ensuring the parsing works for a new issued non fungible
- a test …

Fixed the process_new_issued_token_identifier function and added tests to it

---

contracts/core/price-aggregator/Cargo.toml
contracts/examples/check-pause/Cargo.toml
contracts/examples/crowdfunding-esdt/Cargo.toml
contracts/examples/empty/Cargo.toml
contracts/examples/multisig/Cargo.toml
contracts/feature-tests/rust-testing-framework-tester/Cargo.toml
data/codec-derive/Cargo.toml
data/codec/Cargo.toml
framework/base/Cargo.toml
framework/derive/Cargo.toml
tools/mxpy-snippet-generator/Cargo.toml
vm/Cargo.toml

Exact version dependencies for the base framework, so that reproducible builds are easier to do.
Only changed these dependencies for what ends up in a contract:
- codec
- codec derive
- base
- derive
- wasm-adapter (has no dependency, hail minimalism!)
Did not constrain like this:
- meta crate
- vm
- scenarios
- interactor
- tooling
No changes in the workspace `Cargo.lock` showed me that these are the exact versions we were running with before.

exact deps for base framework

---

data/codec/src/num_conv.rs
data/codec/src/single/top_en_output.rs
framework/base/src/storage/mappers/queue_mapper.rs

`top_encode_number` wasm code:
**Before:**
```
(func $_ZN19multiversx_sc_codec8num_conv17top_encode_number17h070ce2d0e91e3699E (;472;) (type 35) (param i32 i64 i32 i32)
(local i64 i32 i32 i32 i32)
local.get 3
local.get 1
i64.const 56
i64.shl
local.get 1
i64.const 65280
i64.and
i64.const 40
i64.shl
i64.or
local.get 1
i64.const 16711680
i64.and
i64.const 24
i64.shl
local.get 1
i64.const 4278190080
i64.and
i64.const 8
i64.shl
i64.or
i64.or
local.get 1
i64.const 8
i64.shr_u
i64.const 4278190080
i64.and
local.get 1
i64.const 24
i64.shr_u
i64.const 16711680
i64.and
i64.or
local.get 1
i64.const 40
i64.shr_u
i64.const 65280
i64.and
local.get 1
i64.const 56
i64.shr_u
local.tee 4
i64.or
i64.or
i64.or
i64.store align=1
block ;; label = @1
block ;; label = @2
local.get 1
i64.eqz
i32.eqz
br_if 0 …
```

removed all branching from `top_encode_number`

---

framework/base/src/lib.rs
framework/base/src/macros.rs
framework/scenario/tests/contract_without_macros.rs
framework/wasm-adapter/src/lib.rs

We don't actually need a macro to provide the common imports for a smart contract ... a module re-exporting everything does just fine and is friendlier to the IDEs.

imports in modules instead of macros

---

framework/scenario/src/lib.rs

Feature should not be deprecated before a universal replacement exists.

removed deprecation from old testing framework

---

contracts/examples/digital-cash/src/digital_cash.rs
contracts/examples/digital-cash/src/signature_operations.rs
contracts/examples/esdt-transfer-with-fee/src/esdt_transfer_with_fee.rs
contracts/feature-tests/composability/forwarder-raw/src/forwarder_raw_async.rs
contracts/modules/src/token_merge/mod.rs
framework/base/src/contract_base/wrappers/send_wrapper.rs
framework/base/src/types/interaction/tx.rs
framework/base/src/types/interaction/tx_payment.rs
framework/base/src/types/interaction/tx_payment/tx_payment_multi_esdt.rs
framework/base/src/types/managed/multi_value/multi_value_managed_vec.rs

`.multi_esdt(...)` can now be called with a reference directly, and the same time multi_esdt_ref became useless, so I deleted it.

unified syntax - multi esdt reference cleanup

---

framework/scenario/src/api/impl_vh/static_api.rs

In the current implementation, StaticApi doesn't clean its data. It leads to severe memory leaks and therefore it makes the sdk unusable for long running processes such as backend APIs. I started a PR 2 weeks ago to experiment some stuff: https://github.com/multiversx/mx-sdk-rs/pull/1545. However, more work is needed to ensure it won't introduce negative side effects. Anyway, in the meantime we need a way to avoid memory leaks, this is what this PR is about.
Since we need a workaround for this issue, this PR adds a function called `reset` on the StaticApi which resets all the data. After calling this function, StaticApi acts it has never been used, and the old datas held are automatically dropped.
This is a good manual workaround before implementing an automatic data cleaning solution, …

Added reset function on the StaticApi

---

.github/workflows/actions-nightly.yml
.github/workflows/lldb-formatter-tests.yml
.github/workflows/release-upload.yml
.github/workflows/template-test-current.yml
.github/workflows/template-test-released.yml
data/codec/tests/derive_struct_with_generic_test.rs
framework/base/src/types/managed/wrapped/managed_address.rs
framework/wasm-adapter/src/api/managed_types/static_var_api_node.rs
framework/wasm-adapter/src/lib.rs
rust-toolchain.toml

We'll still be supporting nightly Rust builds for a while longer, so I also kept a copy of the actions for running nightly.

Stable Rust: GitHub Actions & toolchain

---

contracts/examples/crowdfunding-esdt/tests/crowdfunding_esdt_blackbox_test.rs
contracts/feature-tests/composability/interact/src/call_tree_deploy.rs
contracts/feature-tests/composability/interact/src/comp_interact_main.rs
framework/snippets/src/interactor_tx.rs
framework/snippets/src/interactor_tx/interactor_exec_call.rs
framework/snippets/src/interactor_tx/interactor_exec_deploy.rs
framework/snippets/src/interactor_tx/interactor_exec_env.rs
framework/snippets/src/interactor_tx/interactor_exec_step.rs
framework/snippets/src/interactor_tx/interactor_exec_transf.rs
framework/snippets/src/interactor_tx/interactor_query_call.rs
framework/snippets/src/interactor_tx/interactor_query_env.rs
framework/snippets/src/interactor_tx/interactor_query_step.rs
framework/snippets/src/multi/homogenous_tx_buffer.rs

Interactor environment rename

---

contracts/examples/nft-minter/src/nft_module.rs
contracts/feature-tests/composability/execute-on-dest-esdt-issue-callback/child/src/lib.rs
contracts/feature-tests/composability/forwarder-legacy/src/forwarder_legacy_main.rs
contracts/feature-tests/composability/forwarder-raw/src/forwarder_raw_async.rs
contracts/feature-tests/composability/forwarder/src/fwd_call_async.rs
contracts/feature-tests/composability/forwarder/src/fwd_esdt.rs
contracts/feature-tests/composability/forwarder/src/fwd_nft.rs
contracts/feature-tests/composability/forwarder/src/fwd_roles.rs
contracts/feature-tests/composability/forwarder/src/fwd_sft.rs
contracts/feature-tests/composability/local-esdt-and-nft/src/lib.rs
contracts/feature-tests/composability/promises-features/src/fwd_call_promise_direct.rs
contracts/feature-tests/composability/promises-features/src/fwd_call_promises_bt.rs
contracts/feature-tests/composability/proxy-test-first/src/proxy-test-first.rs
contracts/feature-tests/composability/recursive-caller/src/recursive_caller.rs
contracts/modules/src/bonding_curve/utils/owner_endpoints.rs
contracts/modules/src/esdt.rs
framework/base/src/storage/mappers/token/non_fungible_token_mapper.rs
framework/base/src/storage/mappers/token/token_mapper.rs
framework/base/src/types/interaction/tx_exec/tx_exec_async.rs
framework/base/src/types/interaction/tx_exec/tx_exec_async_promises.rs

These methods have already caused a lot of confusion, it's time for them to be deprecated.

deprecated legacy methods async_call and async_call_promise

---

contracts/examples/fractional-nfts/src/fractional_uri_info.rs
data/codec/src/codec_err.rs
framework/base/src/api/managed_types/big_int_api.rs
framework/base/src/contract_base/wrappers/blockchain_wrapper.rs
framework/base/src/contract_base/wrappers/serializer.rs
framework/base/src/err_msg.rs
framework/base/src/io/signal_error.rs
framework/base/src/storage/storage_get.rs
framework/base/src/types/managed/basic/cast_to_i64.rs
framework/base/src/types/managed/wrapped/esdt_token_data.rs
framework/base/src/types/managed/wrapped/token_identifier.rs
framework/derive/src/generate/callback_gen.rs

Removed a method that had the potential to add terrible bloat to contracts.
Also made all error messaged be str, for better debugging experience.

Error messages tweak

---

Cargo.lock
contracts/feature-tests/abi-tester/src/abi_test_type.rs
framework/base/src/storage/mappers/vec_mapper.rs
framework/scenario/Cargo.toml
framework/scenario/src/scenario/model/transaction/tx_response.rs
framework/snippets/src/network_response.rs
framework/snippets/tests/test_tx_multiple_sc_results.rs
sdk/core/src/data/transaction.rs

Also cleaned up the Tx converter (network -> scenario).

removed multiversx-sdk dependency from multiversx-sc-scenario

---

framework/base/src/types/interaction/expr/test_address.rs
framework/base/src/types/interaction/expr/test_sc_address.rs
framework/scenario/tests/address_eq_test.rs

Added missing conversion and `==` implementation for test addresses.

test address PartialEq implementation

---

framework/base/Cargo.toml
framework/base/src/types/interaction/tx_data/tx_code_source.rs
framework/base/src/types/interaction/tx_from.rs
framework/base/src/types/interaction/tx_gas.rs
framework/base/src/types/interaction/tx_payment.rs
framework/base/src/types/interaction/tx_result_handler_list/tx_result_handler_list_item.rs
framework/base/src/types/interaction/tx_to.rs

In order to remove rustc 1.78 dependency in 0.50, temporarily removed feature.

temporarily removed diagnostic::on_unimplemented

---

contracts/core/price-aggregator/tests/price_aggregator_blackbox_test.rs
contracts/core/price-aggregator/tests/price_aggregator_stress_blackbox.rs
contracts/examples/rewards-distribution/tests/rewards_distribution_integration_test.rs
contracts/feature-tests/composability/tests/forwarder_whitebox_legacy_test.rs
contracts/feature-tests/composability/tests/forwarder_whitebox_test.rs
contracts/feature-tests/scenario-tester/tests/st_whitebox_deprecated_test.rs
contracts/feature-tests/use-module/tests/token_merge_module_whitebox_test.rs
framework/base/src/types/interaction/expr/test_token_identifier.rs
framework/scenario/src/facade/scenario_world_whitebox.rs

Deprecated the mandos-based whitebox methods.
Also had to migrate some leftover tests.

Whitebox v2 deprecated

---

contracts/examples/adder/interact/.gitignore
contracts/examples/adder/interact/alice.json
contracts/examples/adder/interact/src/basic_interact.rs
framework/snippets/src/imports.rs
sdk/core/src/data/keystore.rs
sdk/core/src/wallet.rs

We modified the function from_keystore_secret to get the password as an argument instead of requesting it from the terminal.

Modified the adder interactor example to work with keystore-signing

---

framework/scenario/src/api/impl_vh/static_api.rs
framework/scenario/src/facade/world_tx/scenario_exec_call.rs
framework/scenario/src/facade/world_tx/scenario_set_state.rs
framework/scenario/src/scenario/model/transaction/tx_response.rs
framework/scenario/src/scenario/model/value/address_key.rs
framework/scenario/src/scenario/model/value/address_value.rs
framework/scenario/src/scenario/run_vm/check_state.rs
framework/scenario/src/scenario/run_vm/sc_call.rs
framework/scenario/src/scenario/run_vm/sc_deploy.rs
framework/scenario/src/scenario/run_vm/sc_query.rs
framework/scenario/src/scenario/run_vm/set_state.rs
framework/scenario/src/scenario/run_vm/transfer.rs
framework/scenario/src/whitebox_legacy/contract_obj_wrapper.rs

Address was deduplicated, so most of the conversions can go away.

Address conversions removed

---

Cargo.lock
sdk/core/src/gateway.rs
sdk/core/src/gateway/gateway_chain_simulator_blocks.rs
sdk/core/src/gateway/gateway_chain_simulator_send_funds.rs
sdk/http/Cargo.toml
sdk/http/src/gateway_http_proxy.rs
sdk/http/src/gateway_http_proxy/http_chain_simulator.rs

sdk - chain simulator requests refactor

---

Cargo.lock
contracts/examples/adder/interact/src/basic_interact.rs
framework/snippets/Cargo.toml
framework/snippets/src/account_tool.rs
framework/snippets/src/interactor.rs
framework/snippets/src/interactor_chain_simulator.rs
framework/snippets/src/interactor_scenario/interactor_sc_call.rs
framework/snippets/src/interactor_scenario/interactor_sc_deploy.rs
framework/snippets/src/interactor_scenario/interactor_transfer.rs
framework/snippets/src/lib.rs
framework/snippets/src/multi/interactor_multi_sc_process.rs
sdk/http/examples/account.rs
sdk/http/examples/account_storage.rs
sdk/http/examples/get_esdt_tokens.rs
sdk/http/examples/get_hyper_block_by_hash.rs
sdk/http/examples/get_hyper_block_by_nonce.rs
sdk/http/examples/get_hyper_block_latest.rs
sdk/http/examples/get_network_config.rs
sdk/http/examples/get_network_economics.rs
sdk/http/examples/sign_tx.rs
sdk/http/examples/sign_txs.rs
sdk/http/examples/tx_cost.rs
sdk/http/examples/tx_default_args.rs
sdk/http/examples/tx_info.rs
sdk/http/examples/vm_query.rs
sdk/http/src/gateway_http_proxy.rs
sdk/http/src/gateway_http_proxy/http_chain_simulator.rs
tools/interactor-system-func-calls/src/system_sc_interact.rs

interactor - chain simulator refactor

---

framework/meta/src/cmd/info.rs
framework/meta/src/cmd/print_util.rs
framework/meta/src/cmd/upgrade.rs
framework/meta/src/cmd/upgrade/upgrade_print.rs
framework/meta/src/cmd/upgrade/upgrade_selector.rs
framework/meta/src/folder_structure/relevant_directory.rs
framework/meta/src/folder_structure/version_req.rs

`sc-meta info` also displays this info in nice colors

sc-meta support for framework deps as path or git

---

contracts/examples/adder/interact/src/basic_interact.rs
contracts/examples/multisig/interact/src/multisig_interact.rs
contracts/examples/multisig/interact/src/multisig_interact_nfts.rs
contracts/examples/multisig/interact/src/multisig_interact_wegld.rs
contracts/examples/ping-pong-egld/dapp/src/interactor.rs
contracts/examples/ping-pong-egld/dapp/src/requests/transaction.rs
contracts/feature-tests/basic-features/interact/src/bf_interact.rs
contracts/feature-tests/composability/interact/src/call_tree_calling_functions.rs
framework/meta-lib/src/contract/generate_snippets/snippet_sc_functions_gen.rs
framework/snippets-base/src/interactor_tx.rs
framework/snippets-base/src/interactor_tx/interactor_exec_call.rs
framework/snippets-base/src/interactor_tx/interactor_exec_deploy.rs
framework/snippets-base/src/interactor_tx/interactor_exec_transf.rs
framework/snippets-base/src/interactor_tx/interactor_exec_upgrade.rs
framework/snippets-base/src/interactor_tx/interactor_prepare_async.rs
framework/snippets-base/src/interactor_tx/interactor_query_call.rs
framework/snippets-dapp/src/imports.rs
framework/snippets/src/imports.rs
tools/interactor-system-func-calls/src/system_sc_interact.rs

Turns out Rust now supports async in traits, but prefers it being spelled out explicitly `... -> std::future:Future<Output = ...>`

unified syntax - removed need for `prepare_async()`

---

framework/base/src/abi/endpoint_abi.rs
framework/base/src/external_view_contract.rs
framework/derive/src/generate/abi_gen.rs
framework/scenario/tests/contract_without_macros.rs

abi - EndpointAbi builder pattern

---

contracts/examples/multisig/interact/src/multisig_interact.rs
contracts/feature-tests/scenario-tester/tests/st_blackbox_test.rs
framework/base/src/types/interaction/result_handlers.rs
framework/base/src/types/interaction/result_handlers/pass_value.rs

Simply passes a value to the result.
The value is constant with respect to the tx, will always be returned, irrespective of the tx execution.
It is especially useful in multi-calls, since it can pass context from the setup section to the result processing section.

unified syntax - PassValue

---

Cargo.lock
framework/snippets/Cargo.toml
sdk/http/Cargo.toml

(Following #1837)
I added a static-tls features in the snippets and sdk-http crates. This feature, when enabled, use a rust implementation of tls, instead of relying on the system's OpenSSL installation.
The goal is to allow developers to cross-compile their projects, especially when the host is a mac arm64 to a linux target (any arch).

Allow for cross-compilation MacOS -> Linux any arch

---

contracts/core/price-aggregator/tests/price_aggregator_whitebox_test.rs
framework/derive/src/contract_impl.rs
framework/derive/src/generate/endpoints_mod_gen.rs
framework/derive/src/generate/function_selector.rs
framework/derive/src/generate/method_call_gen.rs
framework/derive/src/generate/snippets.rs
framework/scenario/tests/contract_without_macros.rs

It allows mutating the contract object.
This is relevant for:
- storage v2
- some experiments I'm performing with call value
Caveat: the contract object creates a new object on `call`, which it can mutate.

EndpointWrappers `call_*` method refactor

---

Cargo.lock
framework/meta/Cargo.toml

The newest version dropped support for rustc 1.80-nightly, which we use for testing backwards compatibility with nightly.

fixed `home` dependency issue in sc-meta

---

contracts/examples/bonding-curve-contract/src/bonding_curve_contract.rs
contracts/examples/crowdfunding-esdt/src/crowdfunding_esdt.rs
contracts/examples/digital-cash/src/pay_fee_and_fund.rs
contracts/examples/digital-cash/src/signature_operations.rs
contracts/examples/esdt-transfer-with-fee/src/esdt_transfer_with_fee.rs
contracts/examples/fractional-nfts/src/fractional_nfts.rs
contracts/examples/lottery-esdt/src/lottery.rs
contracts/examples/multisig/src/multisig.rs
contracts/examples/nft-minter/src/nft_module.rs
contracts/examples/nft-subscription/src/lib.rs
contracts/examples/order-book/pair/src/lib.rs
contracts/examples/rewards-distribution/src/rewards_distribution.rs
contracts/examples/seed-nft-minter/src/nft_module.rs
framework/derive/src/parse/attributes/payable_attr.rs
framework/derive/src/parse/method_parse.rs
framework/derive/src/parse/payable_parse.rs

Syntax simplification. Most of the time, the specific checking of the token is done in code.

payable attribute - `#[payable]`

---

framework/meta/src/cmd/install/install_debugger.rs

This commit aims to provide a clearer error message when attempting to install the available tools using the `sc-meta install all` command, in the rare case when a user has a malformed VSCode **settings.json** file.
For example, let's consider these two **settings.json** file examples:
1. Correct
```json
{
"workbench.iconTheme": "vscode-icons",
"[typescript]": {
"editor.formatOnSave": true,
"editor.defaultFormatter": "vscode.typescript-language-features"
}
}
```
2. Wrong
```json
{
"workbench.iconTheme": "vscode-icons",
"[typescript]": {
"editor.formatOnSave": true,
"editor.defaultFormatter": "vscode.typescript-language-features",
}
}
```
In the second case we have a trailling comma, after the end of the **editor.defaultFormatter** row. While this additional comma won't be a problem for …

Add a clearer panic message if settings.json is malformed

---

framework/base/src/types/interaction/result_handlers/returns_bt_reset.rs
framework/base/src/types/interaction/tx_exec/tx_exec_deploy.rs
framework/base/src/types/interaction/tx_exec/tx_exec_sync.rs
framework/base/src/types/interaction/tx_result_handler_list/tx_result_handler_list_exec.rs
framework/scenario/src/facade/result_handlers/expect_error.rs
framework/scenario/src/facade/result_handlers/expect_message.rs
framework/scenario/src/facade/result_handlers/expect_status.rs
framework/scenario/src/facade/result_handlers/expect_value.rs
framework/scenario/src/facade/result_handlers/returns_handled_or_err.rs
framework/scenario/src/facade/result_handlers/returns_message.rs
framework/scenario/src/facade/result_handlers/returns_status.rs
framework/scenario/src/scenario/tx_to_step/tx_to_step_call.rs
framework/scenario/src/scenario/tx_to_step/tx_to_step_deploy.rs
framework/scenario/src/scenario/tx_to_step/tx_to_step_query.rs
framework/scenario/src/scenario/tx_to_step/tx_to_step_upgrade.rs

unified syntax - result handler preprocessing methods rename

---

.github/workflows/actions.yml
.github/workflows/lldb-formatter-tests.yml
.github/workflows/plotter-test.yml
.github/workflows/proxy-compare.yml
.github/workflows/template-test-current.yml
.github/workflows/template-test-released.yml
framework/meta-lib/src/contract/sc_config/contract_variant.rs
framework/meta-lib/src/contract/sc_config/contract_variant_builder.rs
framework/meta-lib/src/contract/sc_config/contract_variant_settings.rs
framework/meta-lib/src/contract/sc_config/sc_config_serde.rs
framework/meta-lib/src/contract/sc_config/wasm_build.rs
framework/meta-lib/src/tools.rs
framework/meta-lib/src/tools/build_target.rs
framework/meta-lib/src/tools/wasm_opt.rs
framework/meta/src/cmd/code_report/generate_report.rs
framework/meta/src/cmd/code_report/render_code_report.rs
framework/meta/src/cmd/install/install_wasm_tools.rs

Now using target `wasm32v1-none` instead of `wasm32-unknown-unknown`, for rustc >=1.85, to avoid bulk memory operations.
Also added an override in `sc-config.toml`, if anyone ever needs it.
We might revert to `wasm32-unknown-unknown`, but only after we add bulk operation support in the VM.

sc-meta - wasm32v1 default target, rustc target field config

---

contracts/feature-tests/abi-tester/abi_tester_expected_main.abi.json
contracts/feature-tests/abi-tester/abi_tester_expected_view.abi.json
contracts/feature-tests/abi-tester/src/abi_tester.rs
contracts/feature-tests/basic-features/src/event_features.rs
framework/derive/src/parse/auto_impl_parse.rs

Added some tests on top of gfusee's PR: https://github.com/multiversx/mx-sdk-rs/pull/2038
It fixes a bug where #[event] set "" as the event's identifier, instead of the method's name like the #[endpoint] macro.

Event identifier fix + test

---

contracts/feature-tests/composability/forwarder-legacy/src/fwd_esdt_legacy.rs
contracts/feature-tests/composability/forwarder-legacy/src/fwd_nft_legacy.rs
contracts/feature-tests/composability/forwarder-legacy/wasm/src/lib.rs
contracts/feature-tests/composability/tests/composability_scenario_rs_forwarder_legacy_test.rs

`forwarder-legacy` was missing tests. It was copied from `forwarder` some time ago, so most mandos tests are identical.
I set up another test suite which tests the same scenarios with `forwarder-legacy` instead of `forwarder`. Deleted everything that was not relevant.
Did not bother to set up mandos-go tests, only mandos-rs (although it should be possible).
Also found and deleted some code in `forwarder-legacy` that was not in fact testing anything legacy, it was just duplicate.
`forwarder-legacy` will probably not be kept forever anyway.

forwarder-legacy tests & cleanup

---

contracts/feature-tests/composability/forwarder-legacy/src/forwarder_legacy_main.rs
contracts/feature-tests/composability/forwarder-legacy/src/fwd_fallible_legacy.rs
contracts/feature-tests/composability/forwarder-legacy/wasm/src/lib.rs
contracts/feature-tests/composability/scenarios/forw_raw_sync_fallible_legacy.scen.json
contracts/feature-tests/composability/tests/composability_scenario_go_test.rs
contracts/feature-tests/composability/tests/composability_scenario_rs_test.rs
framework/base/src/types/interaction/tx_exec/tx_exec_sync.rs

Requested by @dorin-iancu, because he doesn't like the unified syntax.

Legacy reimagined: execute_on_dest_context_fallible
